### ISSUE TITLE
Can't be remotely installed

### ISSUE THREAD

**Issue by amigrave** [asweigart/pyautogui#101]
Hi,

pyautogui tries to communicate with the X server at install time preventing pyautogui to be remotely installed (eg: when provisioning a desktop trough ssh)

```
$qtile_venv/bin/pip install pyautogui
Collecting pyautogui
  Using cached PyAutoGUI-0.9.33.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pJLhTF/pyautogui/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "pyautogui/__init__.py", line 114, in <module>
        from . import _pyautogui_x11 as platformModule
      File "pyautogui/_pyautogui_x11.py", line 153, in <module>
        _display = Display(None) # TODO - Display() can have other values passed to it. Implement that later.
      File "/home/agr/.local/venvs/qtile/local/lib/python2.7/site-packages/Xlib/display.py", line 89, in __init__
        self.display = _BaseDisplay(display)
      File "/home/agr/.local/venvs/qtile/local/lib/python2.7/site-packages/Xlib/display.py", line 71, in __init__
        protocol_display.Display.__init__(self, *args, **keys)
      File "/home/agr/.local/venvs/qtile/local/lib/python2.7/site-packages/Xlib/protocol/display.py", line 60, in __init__
        name, host, displayno, screenno = connect.get_display(display)
      File "/home/agr/.local/venvs/qtile/local/lib/python2.7/site-packages/Xlib/support/connect.py", line 72, in get_display
        return mod.get_display(display)
      File "/home/agr/.local/venvs/qtile/local/lib/python2.7/site-packages/Xlib/support/unix_connect.py", line 61, in get_display
        raise error.DisplayNameError(display)
    Xlib.error.DisplayNameError: Bad display name ""
```

**Comment by asweigart** [comment]
Currently PyAutoGUI doesn't support remote/headless machines. I've created a master issue #133 to track the development of this feature.
