### ISSUE TITLE
Failed to install on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by ylh888** [asweigart/pyautogui#180]
I tried installing on the latest Raspbian.  I have already installed all the dependencies (pip3 install python3-xlib,scrot, python3-tk,python3-dev

The following is the error message:

sudo pip3 install pyautogui

Downloading/unpacking pyautogui
  Downloading PyAutoGUI-0.9.36.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/tmp/pip-build-okg4qt6s/pyautogui/setup.py) egg_info for package pyautogui
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-okg4qt6s/pyautogui/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "/tmp/pip-build-okg4qt6s/pyautogui/pyautogui/__init__.py", line 115, in <module>
        from . import _pyautogui_x11 as platformModule
      File "/tmp/pip-build-okg4qt6s/pyautogui/pyautogui/_pyautogui_x11.py", line 160, in <module>
        _display = Display(os.environ['DISPLAY'])
      File "/usr/lib/python3.4/os.py", line 633, in __getitem__
        raise KeyError(key) from None
    KeyError: 'DISPLAY'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-okg4qt6s/pyautogui/setup.py", line 6, in <module>

    version=__import__('pyautogui').__version__,

  File "/tmp/pip-build-okg4qt6s/pyautogui/pyautogui/__init__.py", line 115, in <module>

    from . import _pyautogui_x11 as platformModule

  File "/tmp/pip-build-okg4qt6s/pyautogui/pyautogui/_pyautogui_x11.py", line 160, in <module>

    _display = Display(os.environ['DISPLAY'])

  File "/usr/lib/python3.4/os.py", line 633, in __getitem__

    raise KeyError(key) from None

KeyError: 'DISPLAY'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-okg4qt6s/pyautogui
Storing debug log for failure in /root/.pip/pip.log

**Comment by paulie-g** [comment]
This is telling you that $DISPLAY isn't present in your environment. It appears that pyautogui needs X to be running and accessible during install as well as at runtime. This isn't a bug imo.

**Comment by asweigart** [comment]
For what it's worth, PyAutoGUI does seem to work on my raspberry pi virtual machine.
