### ISSUE TITLE
Unable to install pyautogui on Linux if X11 is not running

### ISSUE THREAD

**Issue by mikatammi** [asweigart/pyautogui#184]
root@ubuntu-xenial:~# pip install pyautogui
Collecting pyautogui
  Using cached PyAutoGUI-0.9.36.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-V0xRIK/pyautogui/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "/tmp/pip-build-V0xRIK/pyautogui/pyautogui/__init__.py", line 115, in <module>
        from . import _pyautogui_x11 as platformModule
      File "/tmp/pip-build-V0xRIK/pyautogui/pyautogui/_pyautogui_x11.py", line 160, in <module>
        _display = Display(os.environ['DISPLAY'])
      File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
        raise KeyError(key)
    KeyError: 'DISPLAY'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-V0xRIK/pyautogui/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by mikatammi** [comment]
Seems that there is already another bug with the same issue: #151

**Comment by MadeInChina** [comment]
+1

**Comment by smurfix** [comment]
It'd be nice to have a proper object oriented interface for this instead of depending on a `_display` global that's initialized at startup …
