### ISSUE TITLE
Fail to connect to X Server with error "TypeError: 'type' object does not support ..."

### ISSUE THREAD

**Issue by LittleFrog1959** [asweigart/pyautogui#202]
Hi

I have been using PyAutoGui to connect to X servers running on a LAN.  I use a work around I found to enable this to happen.  It's worked fine up until recently with the introduction of a new remote computer.  A cut down version of the code I use is shown below;

```
import pyautogui
import Xlib

class g:
#    otmXDisplay = "192.168.1.31:0.0"
    otmXDisplay = "10.60.102.11:0.0"

pyautogui.platformModule._display = Xlib.display.Display (g.otmXDisplay)
```
When connecting to all remote X servers previously this has always worked fine.  The new computer fails with the following Python error;

```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    pyautogui.platformModule._display = Xlib.display.Display (g.otmXDisplay)
  File "build/bdist.linux-x86_64/egg/Xlib/display.py", line 127, in __init__
  File "build/bdist.linux-x86_64/egg/Xlib/ext/randr.py", line 1191, in init
  File "build/bdist.linux-x86_64/egg/Xlib/display.py", line 334, in extension_add_subevent
  File "build/bdist.linux-x86_64/egg/Xlib/protocol/display.py", line 329, in add_extension_event
TypeError: 'type' object does not support item assignment
```
I've done my best to look at display.py to see what might be going wrong, but my Python skills are not sufficient to make sense of what I see.

I have taken to a spot of Wiresharking and I can see the following on a working system (this is really cut down, I can post the whole thing if required);
```
Client                               Server
Initial Connection Request ->
                                    <- Reply
GetKeyboardMapping ->
                                    <- Reply
ListExtensions ->
                                    <- Reply
QueryExtension ->                             Repeated for each of the extensions
                                    <- Reply
```
The working connection attempt has 10 extensions, each of which are queried.  I can see that the connection that fails also has a similar list (not sure if there are 10 identical, but they're similar).

The order that they're listed in the "ListExtensions" reply is different on both systems but this does not worry me (not sure why!)

The one that fails always does so on the following one... Query "RANDR".  This is a hand-written summary of a comparison of the two replies;
```
Field                       Fails                      Working
reply                       1                          1
unused
sequencenumber              7                          9
reply length                0                          0
present                  True                         True
major-opcode             139                             140
first-event               88                           89
first-error                145                         147

```
The only thing I can see there is that the op-codes are not the same; is that important?  Not sure.  The response "COMPOSITE" is a different op-code too... 142 on the working system and 140 on the one that fails.

If anyone has any ideas about why these different responses seem to result in a failed connection, I'd be really grateful for your insight.

Thanks

Dave

**Comment by LittleFrog1959** [comment]
Op- Code difference might not be important as it would seem that they are assigned on the fly.

https://www.x.org/wiki/Development/Documentation/Protocol/OpCodes/

"Opcodes 128-255 are dynamically assigned to X extensions...."

**Comment by LittleFrog1959** [comment]
OK.  I kind of got it working....  This is going to make you weep....

I had already installed python-xlib in my home directory and the error occurs in this program;

`~/python-xlib/build/lib.linux-x86_64-2.7/Xlib/protocol/display.py
`

So I added some debug and a try/except around the area that fails like this;

```
    def add_extension_event(self, code, evt, subcode=None):
       fd = open ("delme" , "a")
       fd.write ("Code     " + str (code) + "\n")
       fd.write ("Sub Code " + str (subcode) + "\n")
       fd.write ("Event    " + str (evt) + "\n")
       if subcode == None:
           fd.write ("No supplied sub code \n")
           self.event_classes[code] = evt
       else:
           if not code in self.event_classes:
               fd.write ("No code in event_classes\n")
               self.event_classes[code] = {subcode: evt}
           else:
               fd.write ("Already got code in event_classes\n")
               try:
                   self.event_classes[code][subcode] = evt
               except:
                   fd.write ("Ignored error\n")
       fd.write ("\n")
       fd.close ()

```
After doing these edits, you need to re-install the XLib by entering the following in the python-xlib directory;

`sudo python setup.py install
`

I am not clever enough to understand why it works with one X Server and not another...  The debug does not show anything different apart from the different "First-Events" which I noted in the initial post.  Here is the output from the one that works;
```
Code     64
Sub Code None
Event    <class 'Xlib.ext.shape.NotifyEventData'>
No supplied sub code

Code     89
Sub Code None
Event    <class 'Xlib.ext.randr.ScreenChangeNotify'>
No supplied sub code

Code     90
Sub Code 0
Event    <class 'Xlib.ext.randr.CrtcChangeNotify'>
Already got code in event_classes
```

And the one that fails;
```
Code     64
Sub Code None
Event    <class 'Xlib.ext.shape.NotifyEventData'>
No supplied sub code

Code     88
Sub Code None
Event    <class 'Xlib.ext.randr.ScreenChangeNotify'>
No supplied sub code

Code     89
Sub Code 0
Event    <class 'Xlib.ext.randr.CrtcChangeNotify'>
Already got code in event_classes
Ignored error

Code     89
Sub Code 1
Event    <class 'Xlib.ext.randr.OutputChangeNotify'>
Already got code in event_classes
Ignored error

Code     89
Sub Code 2
Event    <class 'Xlib.ext.randr.OutputPropertyNotify'>
Already got code in event_classes
Ignored error

Code     35
Sub Code None
Event    <class 'Xlib.ext.ge.GenericEvent'>
No supplied sub code
```

Dunno.  Anyway, with this terrible work-around loaded the initialisation continues and then both the mouse moves and clicks work....  That's all I need.

**Comment by BBmykola** [comment]
hey i am facing the same issue. I also did try-catch and it seems to work for now. however i have no file setup.py to reinstall package, and how would it work if we just changed that lib code. Isn't reinstalling it will revert local changes?

Why this issue isn't fixed yet?
