### ISSUE TITLE
install issue on win10 64bit

### ISSUE THREAD

**Issue by broosted** [asweigart/pyautogui#209]
pip install --upgrade pyautogui
Collecting pyautogui
Requirement already up-to-date: PyTweening>=1.0.1 in c:\python27\lib\site-packages (from pyautogui)
Collecting pyscreeze (from pyautogui)
Collecting Pillow (from pyautogui)
  Using cached Pillow-5.0.0-cp27-cp27m-win_amd64.whl
Requirement already up-to-date: pymsgbox in c:\python27\lib\site-packages (from pyautogui)
Installing collected packages: Pillow, pyscreeze, pyautogui
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\python27\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\python27\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\python27\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "c:\python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'c:\\python27\\Lib\\site-packages\\PIL\\_imaging.pyd'

**Comment by scimax** [comment]
I just installed pyautogui v0.9.36 on Windows 10 64-Bit, but for python 3.6.4.

**Comment by alphaCTzo7G** [comment]
you may want to try `pip install --user Pyautogui`... seems like you have a permission error: Permission denied: 'c:\python27\Lib\site-packages\PIL\_imaging.pyd'
