### ISSUE TITLE
Adding pipenv

### ISSUE THREAD

**Issue by afs2015** [asweigart/pyautogui#223]
I think this project could be made easier for new users/contributors if we utilized Pipenv, in particular https://docs.pipenv.org/advanced/#specifying-basically-anything to specify operating system specific requirements.

This way if you wanted to be a contributor and set up a dev environment it would be as simple as `pipenv install --dev` versus checking, then installing which operating system dependencies you need and then pip installing the development dependencies.

**Comment by freshollie** [comment]
Hey!

I see you added support for OSX and Windows, however it seems that Linux wasn't tested?

When I try to install with pipenv on linux:

```
freshollie@freshollie-desktop:~/Documents/Repos/toontown-infinite$ pipenv install pyautogui
Installing pyautogui…
Collecting pyautogui
  Downloading https://files.pythonhosted.org/packages/2e/83/89b5adbc37d1bbf7b486a2c1c00e8037e6f801e8c053c4897bb82d9510c6/PyAutoGUI-0.9.36.tar.gz (46kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i28Tss/pyautogui/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "pyautogui/__init__.py", line 115, in <module>
        from . import _pyautogui_x11 as platformModule
      File "pyautogui/_pyautogui_x11.py", line 7, in <module>
        from Xlib.display import Display
    ImportError: No module named Xlib.display

    ----------------------------------------

Error:  An error occurred while installing pyautogui!
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-i28Tss/pyautogui/
```

Running `pipenv install Xlib` and then reinstalling pyautogui fixed the error.

**Comment by alphaCTzo7G** [comment]
@freshollie, yes this is possible.. https://stackoverflow.com/a/35614580/4752883

**Comment by afs2015** [comment]
@freshollie, yep as @alphaCTzo7G wrote you can add something like `Xlib = {version = "*", sys_platform = "== 'Darwin'"}`to the Pipfile to handle this. I'm happy to update the MR to include that I would just need someone else to test it for me since I only have OSX and Windows handy.

**Comment by alphaCTzo7G** [comment]
@afs2015, Currently, it seems `Pyautogui` uses `setup.py` to determine platform-neutral packages..

However, even `setup.py` can be modified to include `python` specific packages: http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies

Wondering what advantages do you use of adding `pipenv`, and piplock files, over just modifying the `setup.py` files? If we just keep the `setup.py` file, which generally works well.. and just add the platform specific settings, then wont it be simpler?

I haven't dug into `pipenv` too much.. Does this automatically ensure that users who use `pip install Pyautogui` automatically will get the platform-specific libraries as well platform-neutral libraries in one shot?

**Comment by freshollie** [comment]
@alphaCTzo7G I have just reread everything here, and realised the functionality I was looking for was actually the dependency in the `setup.py`....

Sorry for the confusion. The `Pipfile` in the library is supposed to be used for when contributing to the library. It is not, as you said, used by `pipenv` when running `pipenv install pyautogui`.

**Comment by alphaCTzo7G** [comment]
@afs2015, do you want to modify the `setup.py` file and modify your PR then?

It will then help users as well as contributors easily install `pyautogui` on
all platforms, without having to install specific dependencies and have errors.

I can do it as well, but I dont have Mac OS. I can verify on Linux and Windows.

**Comment by alphaCTzo7G** [comment]
@asweigart what do you think?

**Comment by asweigart** [comment]
Yes, I'm in favor of it, in general. I'm buried under other committments right now, but in general I'm open to PRs. You might have to ping/email me to get my attention on it though. Sorry about this. I'm hoping I'll have more time next week to pay attention to PyAutoGUI issues, as I have a lot of ideas for progressing on its roadmap.

**Comment by alphaCTzo7G** [comment]
I created a PR #241 to automatically install the dependencies. 

Because I dont have access to the `pypi` repository, I created a test using
to install `pyautogui` using the local repository itself.


	mkdir ~/tmp;
    cd ~/tmp;
    rm -rf env pyautogui;
    git clone --single-branch -b install_dependencies_wo_user_intervention git@github.com:alphaCTzo7G/pyautogui.git;
    virtualenv --python=$(which python3) env;
    source env/bin/activate;
    pip install -e pyautogui;
    pip list;
    deactivate

Can you guys check if `pip list` in the above sequence shows that the proper 
libraries are being installed for `Mac`.

I have verified that it works fine for `Windows`, `Linux`(`python2` and
`python3`)

cc @afs2015, @freshollie, @shantang96, @jtara1

**Comment by chrahunt** [comment]
The missing Linux platform dependency was fixed in 13c83ce3.
