### ISSUE TITLE
On Windows, SendInput should be called instead of the deprecated mouse_event

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyautogui#23]
To move the mouse on Windows, PyAutoGUI uses the mouse_event API, which is deprecated. We should change it to use SendInput. fx-kirin pointed out in PR 22 https://github.com/asweigart/pyautogui/pull/22 that because mouse_event doesn't cause the "last error" to be updated, the GetLastError() call is misleading at best.

Additional info:

From https://msdn.microsoft.com/en-us/library/windows/desktop/ms680627%28v=vs.85%29.aspx :
From checking out the docs for mouse_event, it seems that it doesn't set the "last error", so really this code shouldn't be calling GetLastError() at all. Since mouse_event is deprecated, this code should be calling SendInput(), which does modify the last error. This would make this commit's addition of SetLastError() unneeded.

What we should probably do is call SendInput() to correct the original problem. Thanks for pointing this out! I'll open an issue for it.

SendInput doc:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms646310(v=vs.85).aspx

**Comment by CTPaHHuK-HEbA** [comment]
```python
import pyautogui
import sqlite3
from time import time

class Test(object):

    def __init__(self):
        connect = sqlite3.connect('test.db')
        connect.isolation_level = None
        self.cursor = connect.cursor()
        self.cursor.execute("DROP TABLE IF EXISTS test")
        self.cursor.execute("CREATE TABLE test (time FLOAT UNIQUE)")

    def ins_t(self):
        self.cursor.execute("INSERT INTO test (time) VALUES (%f)" % time())

T = Test()

T.ins_t()
pyautogui.moveTo(200, 200, 1)
pyautogui.click()

T.ins_t()
pyautogui.moveTo(300, 300, 1)
pyautogui.click()
```
```
Traceback (most recent call last):
  File "I:/watch/bug.py", line 25, in <module>
    pyautogui.click()
  File "C:\Python27\lib\site-packages\pyautogui\__init__.py", line 285, in click
    platformModule._click(x, y, 'left')
  File "C:\Python27\lib\site-packages\pyautogui\_pyautogui_win.py", line 437, in _click
    _sendMouseEvent(MOUSEEVENTF_LEFTCLICK, x, y)
  File "C:\Python27\lib\site-packages\pyautogui\_pyautogui_win.py", line 480, in _sendMouseEvent
    raise ctypes.WinError()
WindowsError: [Error 2] The system cannot find the file specified
```
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
PyAutoGUI (0.9.30)
If delete:
   connect.isolation_level = None
or second:
  T.ins_t() - all ok

**Comment by CTPaHHuK-HEbA** [comment]
It intersects with this error [https://github.com/asweigart/pyautogui/issues/47](url)

**Comment by franklingu** [comment]
For the moment, is there any quick update on this issue?

**Comment by franklingu** [comment]
in my case, although the same exception is thrown, the click actually happened

**Comment by glitchassassin** [comment]
A "quick fix" was proposed by CTPaHHuK-HEbA, commenting out the offending error call:

> Monkey patch:
> Into _pyautogui_win.py comment:
> # if ctypes.windll.kernel32.GetLastError() != 0:
> # raise ctypes.WinError()

I've also submitted a pull request to reimplement properly with SendInput.
