### ISSUE TITLE
Build fails: ValueError: invalid literal for int() with base 10: '/'

### ISSUE THREAD

**Issue by yurivict** [asweigart/pyautogui#232]
```
===>  Configuring for py36-PyAutoGUI-0.9.36
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 6, in <module>
    version=__import__('pyautogui').__version__,
  File "/usr/ports/misc/py-PyAutoGUI/work-py36/PyAutoGUI-0.9.36/pyautogui/__init__.py", line 115, in <module>
    from . import _pyautogui_x11 as platformModule
  File "/usr/ports/misc/py-PyAutoGUI/work-py36/PyAutoGUI-0.9.36/pyautogui/_pyautogui_x11.py", line 160, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.6/site-packages/Xlib/protocol/display.py", line 93, in __init__
    name, host, displayno)
  File "/usr/local/lib/python3.6/site-packages/Xlib/support/connect.py", line 102, in get_auth
    return mod.get_auth(sock, dname, host, dno)
  File "/usr/local/lib/python3.6/site-packages/Xlib/support/unix_connect.py", line 133, in new_get_auth
    addr = bytearray(int(x) for x in octets)
  File "/usr/local/lib/python3.6/site-packages/Xlib/support/unix_connect.py", line 133, in <genexpr>
    addr = bytearray(int(x) for x in octets)
ValueError: invalid literal for int() with base 10: '/'
```

Version 0.9.36 on FreeBSD 11.1 with both python-27 and python-36.

**Comment by yurivict** [comment]
This is really a problem of Xlib.
