### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qha95dhv/pyautogui/

### ISSUE THREAD

**Issue by shantang96** [asweigart/pyautogui#234]
I've tried on 6 different Linux machines, and looked up several websites such as StackOverflow, Github, etc. And I am unable to solve this issue.

The following is my Terminal output:

```
root@8ce5996e165d:/# pip install pyautogui
Collecting pyautogui
  Using cached https://files.pythonhosted.org/packages/2e/83/89b5adbc37d1bbf7b486a2c1c00e8037e6f801e8c053c4897bb82d9510c6/PyAutoGUI-0.9.36.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qha95dhv/pyautogui/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "/tmp/pip-install-qha95dhv/pyautogui/pyautogui/__init__.py", line 115, in <module>
        from . import _pyautogui_x11 as platformModule
      File "/tmp/pip-install-qha95dhv/pyautogui/pyautogui/_pyautogui_x11.py", line 160, in <module>
        _display = Display(os.environ['DISPLAY'])
      File "/usr/lib/python3.6/os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'DISPLAY'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qha95dhv/pyautogui/

```

Any help would be greatly appreciated. Thanks so much in advance.

**Comment by confiq** [comment]
I think you forgot to mention that you are running docker. According to the error you don't run X on your docker
