### ISSUE TITLE
locate* functions fail in Python 3.7

### ISSUE THREAD

**Issue by hollberg** [asweigart/pyautogui#239]
In python 3.7, the locateCenterOnScreen function returns the following errors when the image is located (does NOT fail if there is no matching image). I've run the same code (on Windows 10) with Python 3.6 without error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Py/test37/test37.py", line 4, in <module>
    loc = bot.locateCenterOnScreen('chrome_icon.png')
  File "C:\Py\test37\venv37\lib\site-packages\pyscreeze\__init__.py", line 295, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
  File "C:\Py\test37\venv37\lib\site-packages\pyscreeze\__init__.py", line 266, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
  File "C:\Py\test37\venv37\lib\site-packages\pyscreeze\__init__.py", line 250, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
RuntimeError: generator raised StopIteration

Per the Python 3.7 release notes ([https://docs.python.org/3/whatsnew/3.7.html](https://docs.python.org/3/whatsnew/3.7.html)), it appears this issue derives from the following change:
Due to an oversight, earlier Python versions erroneously accepted the following syntax:
f(1 for x in [1],)

class C(1 for x in [1]):
    pass
Python 3.7 now correctly raises a SyntaxError, as a generator expression always needs to be directly inside a set of parentheses and cannot have a comma on either side, and the duplication of the parentheses can be omitted only on calls. (Contributed by Serhiy Storchaka in bpo-32012 and bpo-32023.)

**Comment by konradtuwr** [comment]
Hello. I have the same problem. Can you describe the solution of this problem a little bit clearer? I don't understand exactly where to use your hint with the comma.

Thanks in advance

**Comment by pknagato4** [comment]
same error, can someone explain?
