### ISSUE TITLE
windows can't install PyAutoGui 0.9.41

### ISSUE THREAD

**Issue by mrmmTED** [asweigart/pyautogui#292]
The log is   
Using cached https://files.pythonhosted.org/packages/f1/54/740939161eb3471e8f7
75ce9b0fcac0e54c36bf63501e51f2cd7158f587d/PyGetWindow-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tedgame\AppData\Local\Temp\pip-install-tqy3ahwx\pygetwindow
\setup.py", line 11, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 905: ille
gal multibyte sequence

0.9.39 is right

**Comment by xiezhedaima9591** [comment]
same issue,I changed the 11th line to 'with open("README.md", "r", encoding='utf-8') as fh:', still reporting the same error.

**Comment by TheSima** [comment]
On Ubuntu 16.04 same error, look at this log:
root@blabla:~# pip3 install pyautogui
Collecting pyautogui
  Downloading https://files.pythonhosted.org/packages/19/ef/438d80abd396fd2d124bd37c07c765f913723c54197c4c809d85c8ff5a43/PyAutoGUI-0.9.41.tar.gz (50kB)
    100% |################################| 51kB 466kB/s
Collecting pymsgbox (from pyautogui)
  Downloading https://files.pythonhosted.org/packages/b6/65/86379ede1db26c40e7972d7a41c69cdf12cc6a0f143749aabf67ab8a41a1/PyMsgBox-1.0.6.zip
Collecting PyTweening>=1.0.1 (from pyautogui)
  Downloading https://files.pythonhosted.org/packages/b9/f8/c32a58d6e4dff8aa5c27e907194d69f3b57e525c2e4af96f39c6e9c854d2/PyTweening-1.0.3.zip
Collecting Pillow (from pyautogui)
  Downloading https://files.pythonhosted.org/packages/8b/e9/5c47710fe383f0582da668302a80a6355fe15c2ce2dde89b50fe34acefa6/Pillow-5.4.1-cp35-cp35m-manylinux1_x86_64.whl (2.0MB)
    100% |################################| 2.0MB 702kB/s
Collecting pyscreeze (from pyautogui)
  Downloading https://files.pythonhosted.org/packages/f3/27/073bf07400943e38b06ba40def60ec489d114fd7356c2db5a2f793454312/PyScreeze-0.1.19.tar.gz
Collecting pygetwindow (from pyautogui)
  Downloading https://files.pythonhosted.org/packages/f1/54/740939161eb3471e8f775ce9b0fcac0e54c36bf63501e51f2cd7158f587d/PyGetWindow-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3vshsuig/pygetwindow/setup.py", line 11, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 903: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3vshsuig/pygetwindow/

**Comment by TheSima** [comment]
[https://github.com/asweigart/PyGetWindow/issues/2](url) - the same problem.

**Comment by buff2017** [comment]
> same issue,I changed the 10th line to 'with open("README.md", "r", encoding='utf-8') as fh:', still reporting the same error.

did u fix this error yet? i got this error , when i tried `pip install pyautogui`

**Comment by buff2017** [comment]
and i tried use `pip install pyautogui===0.9.39` is working for me!

**Comment by TheSima** [comment]
@buff the problem lies in setup dependency "pygetwindow". But [PR](https://github.com/asweigart/PyGetWindow/pull/3) on this problem still opened..

**Comment by zhongxiali** [comment]
I got the same issue and still don't have a solution

**Comment by TheSima** [comment]
@zhongxiali try:
pip install pygetwindow==0.0.1 and then try again install pyautogui

**Comment by fjwCode** [comment]
`conda install pyautogui` is working

**Comment by wuqile** [comment]
> @zhongxiali try:
> pip install pygetwindow==0.0.1 and then try again install pyautogui

is working

**Comment by pythonlw** [comment]
pip install pyautogui===0.9.38     is working

**Comment by Xinxin-Lai** [comment]
> > @zhongxiali try:
> > pip install pygetwindow==0.0.1 and then try again install pyautogui
> 
> is working

Hi there,
Is still not working for me, still threw in error 1 as below, any idea?   

 ERROR: Command errored out with exit status 1:
     command: 'c:\users\xinx**\appdata\local\programs\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xinx**\\AppData\\Local\\Temp\\pip-install-hrwccc2q\\pyautogui\\setup.py'"'"'; __file__='"'"'C:\\Users\\xinx**\\AppData\\Local\\Temp\\pip-install-hrwccc2q\\pyautogui\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xinx**\AppData\Local\Temp\pip-install-hrwccc2q\pyautogui\pip-egg-info'
         cwd: C:\Users\xinx**\AppData\Local\Temp\pip-install-hrwccc2q\pyautogui\
    Complete output (3 lines):
    c:\users\xinxin\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error in PyAutoGUI setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in pyobjc-core;platform_system=="Darwin" at ;platform_system=="Darwin"
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Darkagandal** [comment]
I tried to install the version 0.9.0 and it worked for me

**Comment by Amacorp** [comment]
It doesn't work for me (

**Comment by Chingkhuba** [comment]
> 
> 
> I tried to install the version 0.9.0 and it worked for me

Same for me

**Comment by t-h-rk-turner** [comment]
ERROR: Command errored out with exit status 1:
   command: 'c:\users\pmpig\appdata\local\programs\python\python38\python.exe' 'c:\users\pmpig\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\pmpig\AppData\Local\Temp\pip-build-env-1_3znein\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "c:\users\pmpig\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\users\pmpig\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\users\pmpig\appdata\local\programs\python\python38\lib\site-packages\pip\__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "c:\users\pmpig\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\main.py", line 5, in <module>
      import locale
    File "c:\users\pmpig\appdata\local\programs\python\python38\lib\locale.py", line 16, in <module>
      import re
    File "c:\users\pmpig\appdata\local\programs\python\python38\lib\re.py", line 145, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\pmpig\appdata\local\programs\python\python38\python.exe' 'c:\users\pmpig\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\pmpig\AppData\Local\Temp\pip-build-env-1_3znein\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by atabekdemurtaza** [comment]
Doesn't working for me :(

**Comment by Abderrahmane-Boujendar** [comment]
> I tried to install the version 0.9.0 and it worked for me

worked for me too
