### ISSUE TITLE
Python Version 3.7.2 , PyAutoGui version

### ISSUE THREAD

**Issue by qdwangjianjun** [asweigart/pyautogui#309]
import pyautogui
pyautogui.PAUSE = 2
print(pyautogui.size())
button2 = pyautogui.locateOnScreen("capture.png", confidence=0.8)

Traceback (most recent call last):
  File "E:/Project/AutoTest/guitest.py", line 4, in <module>
    button2 = pyautogui.locateOnScreen("capture.png",minSearchTime=3,grayscale=False, confidence=0.8)
  File "E:\Python37-32\lib\site-packages\pyscreeze\__init__.py", line 271, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
  File "E:\Python37-32\lib\site-packages\pyscreeze\__init__.py", line 255, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
TypeError: _locateAll_python() got an unexpected keyword argument 'confidence'

**Comment by qdwangjianjun** [comment]
link to this issue： https://github.com/asweigart/pyautogui/issues/297

**Comment by Roiman** [comment]
I got the same issue, I think this needs to be updated in the documentation – you have to have OpenCV 
 (https://pypi.org/project/opencv-python/) installed for the confidence argument to work.

**Comment by aptrades** [comment]
I installed **opencv_contrib_python-4.1.1.26-cp35-cp35m-win_amd64** with **python 3.5.**
Then i import numpy,pyautogui,cv2 and use the command :
pyautogui.click('st.png',confidence=0.9) 

i get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: click() got an unexpected keyword argument 'confidence'

Please help.

**Comment by DJ00001** [comment]
python version : 3.7.6, got the same "TypeError: _locateAll_python() got an unexpected keyword argument 'confidence'" error you got.  Read online help and tried pip install opencv-python, but still getting the error like you.  did you ever get an answer?

**Comment by DrMantisTobbogan** [comment]
Just chiming in that this may be related somehow to the version of Windows being run. I can execute the code successfully with one environment in Windows 10 but in the exact same environment (using a venv and the same requirements) on Windows Server 2012 fails.
