### ISSUE TITLE
SyntaxError: 'return' with argument inside generator, when import pyautogui

### ISSUE THREAD

**Issue by adigrabcad** [asweigart/pyautogui#318]
These modules are installed in my virtual environment:
```
Successfully installed Pillow-5.4.1 PyTweening-1.0.3 boto3-1.9.110 botocore-1.12.114 certifi-2019.3.9 chardet-3.0.4 comtypes-1.1.7 docutils-0.14 futures-3.2.0 idna-2.8 jmespath-0.9.4 numpy-1.16.2 pyautogui-0.9.41 pycryptodome-3.7.3 pygetwindow-0.0.4 pymsgbox-1.0.6 pyodbc-4.0.26 pypiwin32-223 pyrect-0.1.4 pyscreeze-0.1.20 python-dateutil-2.8.0 pythonnet-2.3.0 pywin32-224 pywinauto-0.6.6 requests-2.21.0 s3transfer-0.2.0 six-1.12.0 slacker-0.12.0 urllib3-1.24.1 wmi-1.4.9 xlrd-1.2.0
```
Then, when I try to `import pyautogui` i got:
```
>>> import pyautogui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Adrian\Documents\GitHub\eagle-gold\scripts\python\env\lib\site-packages\pyautogui\__init__.py", line 84, in <module>
    import pyscreeze
  File "C:\Users\Adrian\Documents\GitHub\eagle-gold\scripts\python\env\lib\site-packages\pyscreeze\__init__.py", line 168
    yield Box(x, y, needleWidth, needleHeight)
SyntaxError: 'return' with argument inside generator
```

Any recent changes introduce it?

**Comment by SaadeMotion** [comment]
`pip uninstall pyautogui pyscreeze`
`pip install pyautogui==0.9.38 pyscreeze==0.1.18`

**Comment by KolbyFlipper** [comment]
> 
> 
> `pip uninstall pyautogui pyscreeze`
> `pip install pyautogui==0.9.38 pyscreeze==0.1.18`

I have the same problem, this didn't solve it.

**Comment by simula67** [comment]
I think the problem is that you are using Python 2. I tried Python 3 and it seemed to work

**Comment by KolbyFlipper** [comment]
oh, yep I didn't realize I was still on python 2 on this laptop. thanks @simula67 that solved it for me too

**Comment by adigrabcad** [comment]
Yes, sorry to do not mentioned that I'm using Python 2.
Now I'm using `pyautogui-0.9.41` and `pyscreeze-0.1.19` and seems to work. 
Lesson learned: do not rely on the latest version since is not always better then previous one 😄

**Comment by danmattera** [comment]
thanks @adigrabcad. I had the same issue and the two rolls backs you mentioned are what worked for me as well:

Running Python 2.7.15 (Windows 10 if that matters as well) with the most recent versions of each package installed as of writing this (`pyautogui-0.9.42` and `pyscreeze-0.1.20`) throws the error mentioned originally.

uninstalling each one and rolling back one version to `pyautogui-0.9.41`  and `pyscreeze-0.1.19` seems to have resolved this particular issue.

**Comment by NemoHoHaloAi** [comment]
thanks @SaadeMotion , U really help me a lot.

PS: maybe u should run 'pip install Xlib' too.
