### ISSUE TITLE
Use LocateOnScreen with Multiple Monitors

### ISSUE THREAD

**Issue by JohnTravolski** [asweigart/pyautogui#321]
I have an extra monitor plugged into my laptop many times (but not all the time) and I recently noticed that the following code:

```
    import pyautogui
    change_intense_to_calm = pyautogui.locateOnScreen('Intense.png', confidence = 0.9)
    run_script_button_x, run_script_button_y = pyautogui.center(change_intense_to_calm)
    pyautogui.click(run_script_button_x, run_script_button_y)
```

doesn't work when the 'Intense.png" item appears on the second monitor!  It does move the mouse to the position and click if it appears on the primary monitor (the laptop screen), but if the window containing that item is on the secondary monitor, it fails, giving me this error:

```
    Traceback (most recent call last):
      File "E:\test_folder\switch.py", line 18, in <module>
        run_script_button_x, run_script_button_y = pyautogui.center(change_intense_to_calm)
      File "C:\Program Files\Python\Python37\lib\site-packages\pyscreeze\__init__.py", line 407, in center
        return (coords[0] + int(coords[2] / 2), coords[1] + int(coords[3] / 2))
    TypeError: 'NoneType' object is not subscriptable
```

presumably because it's not finding it.

How can I modify my code so that it will find the item and click it regardless of which monitor the window containing it is located on?

**Comment by JohnTravolski** [comment]
Does anybody understand why this doesn't work?

**Comment by jhuels** [comment]
Same issue here.  I assume pyautogui only searches the monitor starting at 0, 0

**Comment by JohnTravolski** [comment]
Does anybody know of a solution?  I'm dying to have this fixed.  It would be so useful if it just worked.

**Comment by jhuels** [comment]
I've just switched to opencv and use image template matching.  Then I've written my own library to take screenshots on multiple screens with ctypes for Windows.  It's not a cross platform solution though.

**Comment by JohnTravolski** [comment]
Is it really so difficult of a fix for this program?

**Comment by pascallo** [comment]
If still relevant for someone on __windows__:

In my opinion the issue is, that the current version of pyscreeze utilizing ImageGrab (Pillow) on windows only uses single-screen grab.

A dirty _quick fix_ in __pyscreeze__ could be:
- enable all_screen grabbing:
 In file: pyscreeze/\_\_init\_\_.py, function: `def _screenshot_win32(imageFilename=None, region=None):` 
 change `im = ImageGrab.grab()` to `im = ImageGrab.grab(all_screens= True)`

- handle new introduced negative coordinates due to multiple monitor:
 In file: pyscreeze/\_\_init\_\_.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
```python
if retVal and sys.platform == 'win32':
    # get the lowest x and y coordinate of the monitor setup
    monitors = win32api.EnumDisplayMonitors()
    x_min = min([mon[2][0] for mon in monitors])
    y_min = min([mon[2][1] for mon in monitors])
    # add negative offset due to multi monitor
    retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
```
- don't forget to add the `import win32api`
 In file: pyscreeze/\_\_init\_\_.py,:
```python
if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
    import win32api # used for multi-monitor fix
    from PIL import ImageGrab

**Comment by hapham117** [comment]
> If still relevant for someone on **windows**:
> 
> In my opinion the issue is, that the current version of pyscreeze utilizing ImageGrab (Pillow) on windows only uses single-screen grab.
> 
> A dirty _quick fix_ in **pyscreeze** could be:
> 
> * enable all_screen grabbing:
>   In file: pyscreeze/__init__.py, function: `def _screenshot_win32(imageFilename=None, region=None):`
>   change `im = ImageGrab.grab()` to `im = ImageGrab.grab(all_screens= True)`
> * handle new introduced negative coordinates due to multiple monitor:
>   In file: pyscreeze/__init__.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
> 
> ```python
> if retVal and sys.platform == 'win32':
>     # get the lowest x and y coordinate of the monitor setup
>     monitors = win32api.EnumDisplayMonitors()
>     x_min = min([mon[2][0] for mon in monitors])
>     y_min = min([mon[2][1] for mon in monitors])
>     # add negative offset due to multi monitor
>     retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
> ```
> 
> * don't forget to add the `import win32api`
>   In file: pyscreeze/__init__.py,:
> 
> ```python
> if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
>     import win32api # used for multi-monitor fix
>     from PIL import ImageGrab
> ```

It works. Thanks alot.

**Comment by jesuspabloalfaro** [comment]
> If still relevant for someone on **windows**:
> 
> In my opinion the issue is, that the current version of pyscreeze utilizing ImageGrab (Pillow) on windows only uses single-screen grab.
> 
> A dirty _quick fix_ in **pyscreeze** could be:
> 
> * enable all_screen grabbing:
>   In file: pyscreeze/__init__.py, function: `def _screenshot_win32(imageFilename=None, region=None):`
>   change `im = ImageGrab.grab()` to `im = ImageGrab.grab(all_screens= True)`
> * handle new introduced negative coordinates due to multiple monitor:
>   In file: pyscreeze/__init__.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
> 
> ```python
> if retVal and sys.platform == 'win32':
>     # get the lowest x and y coordinate of the monitor setup
>     monitors = win32api.EnumDisplayMonitors()
>     x_min = min([mon[2][0] for mon in monitors])
>     y_min = min([mon[2][1] for mon in monitors])
>     # add negative offset due to multi monitor
>     retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
> ```
> 
> * don't forget to add the `import win32api`
>   In file: pyscreeze/__init__.py,:
> 
> ```python
> if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
>     import win32api # used for multi-monitor fix
>     from PIL import ImageGrab
> ```

+1 on this working. Thanks pascallo

**Comment by DavidLeeberman** [comment]
@pascallo 
Hi Pascallo, I test Selenium for Python with PyAutoGUI on a display with 2 monitors. I modified pyscreeze/__init__.py as you said but then I got the following error:

 File "e:\test_automation\test.py", line 90, in login_input
    center_x, center_y = pyautogui.locateCenterOnScreen('username_input_box.png')
  File "D:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "D:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\site-packages\pyautogui\__init__.py", line 207, in locateCenterOnScreen
    return pyscreeze.locateCenterOnScreen(*args, **kwargs)
  File "D:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 408, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
  File "D:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 360, in locateOnScreen
    screenshotIm = screenshot(region=None) # the locateAll() function must handle cropping to return accurate coordinates, so don't pass a region here.
  File "D:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 135, in wrapper
    raise PyScreezeException('The Pillow package is required to use this function.')
pyscreeze.PyScreezeException: The Pillow package is required to use this function.

I tried uninstall pillow and then reinstall it with the latest version 8.0.1. It's still not working. Could you please help me look into it? Thanks in advance.

**Comment by Maracaipe611** [comment]
Add these 3 lines to the top of your code to enable all monitor screengrabs in Windows:

from PIL import ImageGrab
from functools import partial
ImageGrab.grab = partial(ImageGrab.grab, all_screens=True)

**Comment by InstDev** [comment]
@Maracaipe611. Thanks alot. Best solution

**Comment by tgajdo** [comment]
Unfortunately this is still an issue. @Maracaipe611 suggestion doesn't seem to work for me, I still get None as response.

**Comment by manniL** [comment]
The solution from @Maracaipe611 worked fine for my dual screen setup ☺️

**Comment by hur-kyuh-leez** [comment]
@Maracaipe611 's solution works! thanks :)

**Comment by gavinlws96** [comment]
@Maracaipe611 Thank you, it worked for me! :)

**Comment by schlechr** [comment]
Hey,
I made the changes in the `locateOnScreen(...)` function, but this didn't work for me everywhere, as I am also using the locateAllOnScreen function.
Maybe somebody needs this as well so here is what I did:
I deleted the part in the `locateOnScreen(...)` function and instead worked in the `_locateAll_opencv(...)` function. At the beginning of the function I added:

```
if sys.platform == 'win32':
        # get the lowest x and y coordinate of the monitor setup
        monitors = win32api.EnumDisplayMonitors()
        x_min = min([mon[2][0] for mon in monitors])
        y_min = min([mon[2][1] for mon in monitors])
```
The reason for that is, that I already need these values when the `haystackImage` gets defined. I subtracted these values after the `if region:` so that the defined region will be used "correctly"

```
haystackImage = haystackImage[region[1]-y_min:region[1]-y_min+region[3],
                              region[0]-x_min:region[0]-x_min+region[2]]
```

And at the end of the function the values needs to be added, like it was done in the single location.

```
for x, y in zip(matchx, matchy):
    yield Box(x + x_min, y + y_min, needleWidth, needleHeight)
```

The same would be needed to be done at the `_locateAll_python(...)` function if you do not use OpenCV (if I understood this correctly), but for me the solution works so far.

**Comment by irineujba** [comment]
Looking for a solution to this problem, I visited the official documentation website and I saw this:

Q: Does PyAutoGUI work on multi-monitor setups.

A: No, right now PyAutoGUI only handles the primary monitor.

**Comment by asyankeesfan** [comment]
This would be amazing if it worked but I keep getting **"retVal is not defined"** after importing win32api and pyautogui and pyscreeze

Is this not the right way to write it?:
![image](https://user-images.githubusercontent.com/93793320/206550576-6d8f1f34-3f60-49c2-bbac-cadceb186ad2.png)

**Comment by StevePic95** [comment]
> This would be amazing if it worked but I keep getting **"retVal is not defined"** after importing win32api and pyautogui and pyscreeze
> 
> 
> 
> Is this not the right way to write it?:
> 
> ![image](https://user-images.githubusercontent.com/93793320/206550576-6d8f1f34-3f60-49c2-bbac-cadceb186ad2.png)
> 
> 

If I'm reading it correctly, you just need to call the locateOnScreen() function after defining it. The definition itself won't assign anything to retVal.

**Comment by asyankeesfan** [comment]
> > This would be amazing if it worked but I keep getting **"retVal is not defined"** after importing win32api and pyautogui and pyscreeze
> > Is this not the right way to write it?:
> > ![image](https://user-images.githubusercontent.com/93793320/206550576-6d8f1f34-3f60-49c2-bbac-cadceb186ad2.png)
> 
> If I'm reading it correctly, you just need to call the locateOnScreen() function after defining it. The definition itself won't assign anything to retVal.
> 
> You may also need to take the period out of the first argument name. (I think it should just be called image if I'm reading your code right)

Thanks for replying. It should look like this?: 
![image](https://user-images.githubusercontent.com/93793320/206567730-da13edd5-3f42-45ef-9353-a2345a84ac34.png)
Shouldn't I specify to which image I wish to locate? It still gives retVal is not defined. Also, I previously had some errors with including **kwargs for some reason but that isn't showing here

**Comment by asyankeesfan** [comment]
@pascallo @Maracaipe611 Could someone possibly include an exact representation of the script they run to allow "locateOnScreen" to function on other monitors?

**Comment by StevePic95** [comment]
@asyankeesfan Sorry, I thought you were trying to define a new function called locateOnScreen(). You shouldn't have a function definition at all. The locateOnScreen function has already been defined, so all you need to do is call it.

Remove the first line entirely (the function definition), then unindent the second line and replace "image" with the actual name of the image (you may have to provide a full path to the image if it's not sitting in the same directory the program is being run from). Make sure the image name is surrounded by single or double quotes to denote that it is a string. You should also remove "**kwargs", which is something you would only use if you were defining a new function.

In simple terms, delete the first two lines and replace them with this line:
`retVal = locateOnScreen("path/to/PoolingFee.png", minSearchTime=0)`

The locateOnScreen() function should store the coordinates where the image is located into retVal, which should allow the rest of the code to work properly.

Please don't take this the wrong way, as I mean this to be helpful, but you will probably benefit hugely from learning the basics of Python first before taking on projects like this. These are some pretty basic errors, and trust me, I've been there before, but you can avoid lots of frustration in the future by just hunkering down for a week or two and getting a solid grasp on the fundamentals. If you're into books, I highly recommend "Automate the Boring Stuff with Python".

**Comment by asyankeesfan** [comment]
@manniL @hapham117 @pascallo @OliverTrust @JohnTravolski @DavidLeeberman @jesuspabloalfaro 

I tried the above code but no luck. Is this just out-dated? Could someone please share their functioning script?

**Comment by asyankeesfan** [comment]
Can anyone provide an example of their script that allows all monitors?

**Comment by nalex09** [comment]
> If still relevant for someone on **windows**:
> 
> In my opinion the issue is, that the current version of pyscreeze utilizing ImageGrab (Pillow) on windows only uses single-screen grab.
> 
> A dirty _quick fix_ in **pyscreeze** could be:
> 
> * enable all_screen grabbing:
>   In file: pyscreeze/__init__.py, function: `def _screenshot_win32(imageFilename=None, region=None):`
>   change `im = ImageGrab.grab()` to `im = ImageGrab.grab(all_screens= True)`
> * handle new introduced negative coordinates due to multiple monitor:
>   In file: pyscreeze/__init__.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
> 
> ```python
> if retVal and sys.platform == 'win32':
>     # get the lowest x and y coordinate of the monitor setup
>     monitors = win32api.EnumDisplayMonitors()
>     x_min = min([mon[2][0] for mon in monitors])
>     y_min = min([mon[2][1] for mon in monitors])
>     # add negative offset due to multi monitor
>     retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
> ```
> 
> * don't forget to add the `import win32api`
>   In file: pyscreeze/__init__.py,:
> 
> ```python
> if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
>     import win32api # used for multi-monitor fix
>     from PIL import ImageGrab
> ```

It works. Thanks!

**Comment by pawel-j-a** [comment]
> If still relevant for someone on **windows**:
> 
> In my opinion the issue is, that the current version of pyscreeze utilizing ImageGrab (Pillow) on windows only uses single-screen grab.
> 
> A dirty _quick fix_ in **pyscreeze** could be:
> 
> * enable all_screen grabbing:
>   In file: pyscreeze/__init__.py, function: `def _screenshot_win32(imageFilename=None, region=None):`
>   change `im = ImageGrab.grab()` to `im = ImageGrab.grab(all_screens= True)`
> * handle new introduced negative coordinates due to multiple monitor:
>   In file: pyscreeze/__init__.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
> 
> ```python
> if retVal and sys.platform == 'win32':
>     # get the lowest x and y coordinate of the monitor setup
>     monitors = win32api.EnumDisplayMonitors()
>     x_min = min([mon[2][0] for mon in monitors])
>     y_min = min([mon[2][1] for mon in monitors])
>     # add negative offset due to multi monitor
>     retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
> ```
> 
> * don't forget to add the `import win32api`
>   In file: pyscreeze/__init__.py,:
> 
> ```python
> if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
>     import win32api # used for multi-monitor fix
>     from PIL import ImageGrab
> ```

Hi, i have 3 monitors in configuration 3 : 2 : 1. Display 2 is my primary and my coords starts with 0.0 on this display. Monitor no 3 has negative coords (negative X to be clear). Your way what you type is working for me if i don't have negative coords.

**Comment by roshanboys** [comment]
If still relevant for someone on windows:
I faced exactly same problem and I found another easy way around which is working for me. 
Since the pyautogui is always searching in primary display, x and y coordinates for it is 0,0.
Easy way is to move the program where pyautogui is used to 0,0, irrespective where it is opened. 
I am using win32gui library for it. 
Here is snippet of the code which worked for me:

import win32gui
import pyautogui
import win32con
program_window = find_window("Program Name") #Replace with program name needed. 

if program_window is not None:

    # Move the window to X=0, Y=0
    win32gui.SetWindowPos(program_window, win32con.HWND_TOP, 0, 0, 0, 0, win32con.SWP_NOSIZE | win32con.SWP_NOZORDER)
    time.sleep(1)
    # Maximize the window
    win32gui.ShowWindow(program_window, win32con.SW_MAXIMIZE)
    time.sleep(2)
    pyautogui.locateOnScreen(reference_image, grayscale=True, region=(0, 0, 1920, 1080), confidence=0.9) is not None:
    

By this pyautogui will always work and it is also possible to capture the original screen coordinate of the program_window and move it back after finishing the required pyautogui operations. 
program_rect = win32gui.GetWindowRect(program_window)

**Comment by asyankeesfan** [comment]
> If still relevant for someone on windows: I faced exactly same problem and I found another easy way around which is working for me. Since the pyautogui is always searching in primary display, x and y coordinates for it is 0,0. Easy way is to move the program where pyautogui is used to 0,0, irrespective where it is opened. I am using win32gui library for it. Here is snippet of the code which worked for me:
> 
> import win32gui import pyautogui import win32con program_window = find_window("Program Name") #Replace with program name needed.
> 
> if program_window is not None:
> 
> ```
> # Move the window to X=0, Y=0
> win32gui.SetWindowPos(program_window, win32con.HWND_TOP, 0, 0, 0, 0, win32con.SWP_NOSIZE | win32con.SWP_NOZORDER)
> time.sleep(1)
> # Maximize the window
> win32gui.ShowWindow(program_window, win32con.SW_MAXIMIZE)
> time.sleep(2)
> pyautogui.locateOnScreen(reference_image, grayscale=True, region=(0, 0, 1920, 1080), confidence=0.9) is not None:
> ```
> 
> def find_window(title, class_name=None): def callback(hwnd, hwnd_list): if class_name is not None: if win32gui.GetClassName(hwnd) == class_name and win32gui.IsWindowVisible(hwnd): hwnd_list.append(hwnd) else: if win32gui.GetWindowText(hwnd) == title and win32gui.IsWindowVisible(hwnd): hwnd_list.append(hwnd) return True hwnd_list = [] win32gui.EnumWindows(callback, hwnd_list) if hwnd_list: return hwnd_list[0] else: return None
> 
> By this pyautogui will always work and it is also possible to capture the original screen coordinate of the program_window and move it back after finishing the required pyautogui operations. program_rect = win32gui.GetWindowRect(program_window)


**### What did you mean by "program name"?**

Also, it gave errors for "find-window" command so I tried using "win32gui.FindWindow"

Is this formatting correct?:

"

import win32gui
import pyautogui
import win32con
import time

program_window = win32gui.FindWindow(None, "New Home.py") 

if program_window is not None: # Move the window to X=0, Y=0
    win32gui.SetWindowPos(program_window, win32con.HWND_TOP, 0, 0, 0, 0, win32con.SWP_NOSIZE | win32con.SWP_NOZORDER)
    time.sleep(1)
    # Maximize the window
    win32gui.ShowWindow(program_window, win32con.SW_MAXIMIZE)
    time.sleep(2)
    pyautogui.locateOnScreen('Save&Close.png', confidence=0.9)
    def find_window(title, class_name=None):
        def callback(hwnd, hwnd_list):
            if class_name is not None:
                if win32gui.GetClassName(hwnd) == class_name and win32gui.IsWindowVisible(hwnd):
                    hwnd_list.append(hwnd)
            else:
                if win32gui.GetWindowText(hwnd) == title and win32gui.IsWindowVisible(hwnd):
                    hwnd_list.append(hwnd)
            return True
        hwnd_list = []
        win32gui.EnumWindows(callback, hwnd_list)
        if hwnd_list:
            return hwnd_list[0]
        else:
            return None

"

For reference, "New Home.png" holds all of my code (using pyautogui and locateOnScreen) and my test 'needle' image is "Save&Close.png". 

All help is appreciated greatly!!

**Comment by kawsarlog** [comment]
> If still relevant for someone on **windows**:
> 
> In my opinion the issue is, that the current version of pyscreeze utilizing ImageGrab (Pillow) on windows only uses single-screen grab.
> 
> A dirty _quick fix_ in **pyscreeze** could be:
> 
> * enable all_screen grabbing:
>   In file: pyscreeze/__init__.py, function: `def _screenshot_win32(imageFilename=None, region=None):`
>   change `im = ImageGrab.grab()` to `im = ImageGrab.grab(all_screens= True)`
> * handle new introduced negative coordinates due to multiple monitor:
>   In file: pyscreeze/__init__.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
> 
> ```python
> if retVal and sys.platform == 'win32':
>     # get the lowest x and y coordinate of the monitor setup
>     monitors = win32api.EnumDisplayMonitors()
>     x_min = min([mon[2][0] for mon in monitors])
>     y_min = min([mon[2][1] for mon in monitors])
>     # add negative offset due to multi monitor
>     retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
> ```
> 
> * don't forget to add the `import win32api`
>   In file: pyscreeze/__init__.py,:
> 
> ```python
> if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
>     import win32api # used for multi-monitor fix
>     from PIL import ImageGrab
> ```

**You are a Lifesaver, this has worked perfectly for me!**

**Comment by dhust** [comment]
I'm surprised there hasn't been a solution for this. Maybe the one above works for two monitors but I'm having coordinate issues with three. I use `pyautogui.position()` or `pyautogui.displayMousePosition()` and it's just not correct, which is probably also causing location issues for clicks.

**Comment by glauciofonsecaa** [comment]
> If still relevant for someone on **windows**:
> 
> In my opinion the issue is, that the current version of pyscreeze utilizing ImageGrab (Pillow) on windows only uses single-screen grab.
> 
> A dirty _quick fix_ in **pyscreeze** could be:
> 
>     * enable all_screen grabbing:
>       In file: pyscreeze/__init__.py, function: `def _screenshot_win32(imageFilename=None, region=None):`
>       change `im = ImageGrab.grab()` to `im = ImageGrab.grab(all_screens= True)`
> 
>     * handle new introduced negative coordinates due to multiple monitor:
>       In file: pyscreeze/__init__.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
> 
> 
> ```python
> if retVal and sys.platform == 'win32':
>     # get the lowest x and y coordinate of the monitor setup
>     monitors = win32api.EnumDisplayMonitors()
>     x_min = min([mon[2][0] for mon in monitors])
>     y_min = min([mon[2][1] for mon in monitors])
>     # add negative offset due to multi monitor
>     retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
> ```
> 
>     * don't forget to add the `import win32api`
>       In file: pyscreeze/__init__.py,:
> 
> 
> ```python
> if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
>     import win32api # used for multi-monitor fix
>     from PIL import ImageGrab
> ```

Its work, thank you Pascallo.
Python 3.12.1
pyautogui 0.9.54

**Comment by asyankeesfan** [comment]
> If still relevant for someone on **windows**:
> 
> In my opinion the issue is, that the current version of pyscreeze utilizing ImageGrab (Pillow) on windows only uses single-screen grab.
> 
> A dirty _quick fix_ in **pyscreeze** could be:
> 
> * enable all_screen grabbing:
>   In file: pyscreeze/__init__.py, function: `def _screenshot_win32(imageFilename=None, region=None):`
>   change `im = ImageGrab.grab()` to `im = ImageGrab.grab(all_screens= True)`
> * handle new introduced negative coordinates due to multiple monitor:
>   In file: pyscreeze/__init__.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
> 
> ```python
> if retVal and sys.platform == 'win32':
>     # get the lowest x and y coordinate of the monitor setup
>     monitors = win32api.EnumDisplayMonitors()
>     x_min = min([mon[2][0] for mon in monitors])
>     y_min = min([mon[2][1] for mon in monitors])
>     # add negative offset due to multi monitor
>     retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
> ```
> 
> * don't forget to add the `import win32api`
>   In file: pyscreeze/__init__.py,:
> 
> ```python
> if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
>     import win32api # used for multi-monitor fix
>     from PIL import ImageGrab
> ```

@pascallo This (pyautogui.locateOnScreen) worked UNTIL I tried to use 'region' parameter. It seems to shift my pixels somehow. The pyautogui.position function does not seem to correlate with the region coordinates anymore. 
So, it works if I scan the whole screen, but not for a specific region

**Comment by asyankeesfan** [comment]
> > If still relevant for someone on **windows**:
> > In my opinion the issue is, that the current version of pyscreeze utilizing ImageGrab (Pillow) on windows only uses single-screen grab.
> > A dirty _quick fix_ in **pyscreeze** could be:
> > 
> > * enable all_screen grabbing:
> >   In file: pyscreeze/**init**.py, function: `def _screenshot_win32(imageFilename=None, region=None):`
> >   change `im = ImageGrab.grab()` to `im = ImageGrab.grab(all_screens= True)`
> > * handle new introduced negative coordinates due to multiple monitor:
> >   In file: pyscreeze/**init**.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
> > 
> > ```python
> > if retVal and sys.platform == 'win32':
> >     # get the lowest x and y coordinate of the monitor setup
> >     monitors = win32api.EnumDisplayMonitors()
> >     x_min = min([mon[2][0] for mon in monitors])
> >     y_min = min([mon[2][1] for mon in monitors])
> >     # add negative offset due to multi monitor
> >     retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * don't forget to add the `import win32api`
> >   In file: pyscreeze/**init**.py,:
> > 
> > ```python
> > if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
> >     import win32api # used for multi-monitor fix
> >     from PIL import ImageGrab
> > ```
> 
> **You are a Lifesaver, this has worked perfectly for me!**


This seems to not coorespond to the "locateCenterOnScreen". 
Just test it and use auto.moveTo and it should put the cursor on the image of auto.locateCenterOnScreen but it doesn't. Any fix to this?

**Comment by BaconEggsRL** [comment]
man it's 2024 we still don't have pyautogui on multiple monitors?

**Comment by auravan** [comment]
hello. I found that  just motify the `allScreens` params to Ture is engouh for me.
In file: `pyscreeze/__init__.py`, function:` def _screenshot_win32(imageFilename=None, region=None,allScreens=False)`

**Comment by fhgisi** [comment]
> from PIL import ImageGrab
> from functools import partial
> ImageGrab.grab = partial(ImageGrab.grab, all_screens=True)

Did not work for me.

**Comment by cphoenix0** [comment]
This worked for me:
Inside `pyscreeze.__init__.py`, go to the function `locateOnScreen`. Add an argument `allScreens=False`. Then, replace the line `screenshotIm = screenshot(region=None)` with `screenshotIm = screenshot(region=None, allScreens=allScreens)`. 

And then do

> * handle new introduced negative coordinates due to multiple monitor:
>   In file: pyscreeze/__init__.py, function: `def locateOnScreen(image, minSearchTime=0, **kwargs):` behind `retVal = locate(image, screenshotIm, **kwargs)` add
> 
> ```python
> if retVal and sys.platform == 'win32':
>     # get the lowest x and y coordinate of the monitor setup
>     monitors = win32api.EnumDisplayMonitors()
>     x_min = min([mon[2][0] for mon in monitors])
>     y_min = min([mon[2][1] for mon in monitors])
>     # add negative offset due to multi monitor
>     retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])
> ```
> 
> * don't forget to add the `import win32api`
>   In file: pyscreeze/__init__.py,:
> 
> ```python
> if sys.platform == 'win32': # TODO - Pillow now supports ImageGrab on macOS.
>     import win32api # used for multi-monitor fix
>     from PIL import ImageGrab
> ```

Note you may need to `pip install pywin32` if `import win32api` is telling you there's no win32api.

So the function `pyscreeze.__init__.locateOnScreen` will now look like:

``` python
def locateOnScreen(image, minSearchTime=0, 
                   allScreens=False, # ADDED THIS ARGUMENT
                    **kwargs):
    start = time.time()
    while True:
        try:
            #screenshotIm = screenshot(region=None)                          # REMOVED THIS LINE
            screenshotIm = screenshot(region=None, allScreens=allScreens)    # ADDED THIS LINE
            retVal = locate(image, screenshotIm, **kwargs)
            try:
                screenshotIm.fp.close()
            except AttributeError:
                pass

            if retVal and sys.platform == 'win32':
                # get the lowest x and y coordinate of the monitor setup
                monitors = win32api.EnumDisplayMonitors()
                x_min = min([mon[2][0] for mon in monitors])
                y_min = min([mon[2][1] for mon in monitors])
                # add negative offset due to multi monitor
                retVal = Box(left=retVal[0] + x_min, top=retVal[1] + y_min, width=retVal[2], height=retVal[3])

            if retVal or time.time() - start > minSearchTime:
                return retVal
        except ImageNotFoundException:
            if time.time() - start > minSearchTime:
                if USE_IMAGE_NOT_FOUND_EXCEPTION:
                    raise
                else:
                    return None
```

And so when you call `locateOnScreen`, you can pass `allScreens=True`.

The other method suggested in this thread,

> from PIL import ImageGrab
from functools import partial
ImageGrab.grab = partial(ImageGrab.grab, all_screens=True)

, does not work for the latest version of `pyscreeze` because the place where `ImageGrab.grab` is called (inside `pyscreeze._screenshot_win32`) was updated at some point to implicitly support `all_screens`. The problem now is that `pyscreeze.locateOnScreen` is not passing the all_screen parameter to `_screenshot_win32`, hence why the fix I found works.
