### ISSUE TITLE
Xlib.error.DisplayConnectionError on Ubuntu 18.04

### ISSUE THREAD

**Issue by jaeger-2601** [asweigart/pyautogui#322]
Importing pyautogui in Python 3.7.2 in Ubuntu 18.04, generates a Xlib.error.DisplayConnectionError
This error only occurs when running python with superuser privileges.

This the full traceback :-
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyautogui/__init__.py", line 152, in <module>
    from . import _pyautogui_x11 as platformModule
  File "/usr/local/lib/python3.7/site-packages/pyautogui/_pyautogui_x11.py", line 160, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.7/site-packages/Xlib/protocol/display.py", line 167, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n
```

Steps to reproduce:-
- run ```sudo python3``` in the terminal
- run ``` import pyautogui ```inside the python 3 shell

**Comment by vanhoutm-elevate** [comment]
Same issue on Ubuntu 19.04 python 3.7.3. Slightly different traceback when calling it from a file.
```
Traceback (most recent call last):
  File "/tmp/test.py", line 2, in <module>
    import pyautogui
  File "/usr/local/lib/python3.7/dist-packages/pyautogui/__init__.py", line 80, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.7/dist-packages/mouseinfo/__init__.py", line 143, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.7/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
```

**Comment by NerveCoordinator** [comment]
Same issue on Ubuntu 19.04 python 3.7.3. Slightly different traceback when calling it from a file.
```
Traceback (most recent call last):
  File "/tmp/test.py", line 2, in <module>
    import pyautogui
  File "/usr/local/lib/python3.7/dist-packages/pyautogui/__init__.py", line 80, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.7/dist-packages/mouseinfo/__init__.py", line 143, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.7/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
```

**Comment by bobthebuilderj** [comment]
Same issue on ubuntu 19.10 python 3.7.5.

**Comment by TyrelCB** [comment]
Anyone find a solution?

**Comment by bobthebuilderj** [comment]
Try 
https://github.com/mooz/xkeysnail/blob/master/README.md(look at usage section)

worked for me.

**Comment by notyash** [comment]
> Try
> https://github.com/mooz/xkeysnail/blob/master/README.md(look at usage section)
> 
> worked for me.

 broken link

**Comment by JcdeA** [comment]
fixed link

**Comment by predly** [comment]
Any news on that bug?

**Comment by Axaxin** [comment]
Same issue on ubuntu 20.04 python 3.8.10
system is on a VM, connect via noVNC... i think this is very common situation using linux, isnt it?

**Comment by Axaxin** [comment]
> Same issue on ubuntu 20.04 python 3.8.10 system is on a VM, connect via noVNC... i think this is very common situation using linux, isnt it?

ok, issue resolve by installing python-tk (not python3-tk), then restart terminal or system, then it works.
As the installation guide, i did install acrot, python3-tk and python3-dev, but it turn out not working, I'm not sure if I had restarted terminal right after these packs install, but I did restart after python-tk, then everything work.

Not sure if both python3-tk and python-tk are needed, or just python-tk alone.

**Comment by Rhythmicbinary** [comment]
I had the same problem, but using the `xhost +SI:localuser:root` command solved the problem.

**Comment by protokoul** [comment]
Tried this command in Ubuntu 25.04 inside Virtualbox but it didn't work. Seems that Ubuntu now strictly enforces Wayland because I edited /etc/gdm3/custom.conf, commented the line `WaylandEnable = False`, rebooted the VM and my script still returned the same error.
