### ISSUE TITLE
PyAutoGui/PyScreeze incompatability

### ISSUE THREAD

**Issue by domluther** [asweigart/pyautogui#328]
I use coords = pyautogui.locateCenterOnScreen() and it returns a list of the co-ordinates in int64 format.

I then use pyautogui.pixel(coords) on that to try to work out what colour that pixel is and hit an error because pixel() on Windows seems to only handle int and not int64. The relevant error message is..

```
color = windll.gdi32.GetPixel(hdc, x, y)
ctypes.ArgumentError: argument 3: <class 'TypeError'>: Don't know how to convert parameter 3
```

Am I using this wrong? The only way I can get around this is to manually cast the returned coords to regular int and then it works perfectly.

**Comment by paulwrath1223** [comment]
I Have the same problem, except mine is parameter 2
here is my error message: 
Traceback (most recent call last):
  File "C:\Users\julia\Dropbox\Python programs\scratch game bot.py", line 33, in <module>
    pix = pyautogui.pixel(xco, yco)
  File "C:\Users\julia\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyscreeze\__init__.py", line 447, in pixel
    color = windll.gdi32.GetPixel(hdc, x, y)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: Don't know how to convert parameter 2


Windows 10

**Comment by Sai-Prabhav** [comment]
even i have the same problem...

Traceback (most recent call last):
  File "c:\Users\CSC\Desktop\my code\python\dino.py", line 44, in <module>
    v = pixel(mp+20, h)
  File "C:\Users\CSC\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 578, in pixel
    color = windll.gdi32.GetPixel(hdc, x, y)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: Don't know how to convert parameter 2

**Comment by Blues-star** [comment]
the same to me, i got the same error text
`    p = tuple(ag.pixel(x, y))
  File "C:\Users\P7XXTM1-G\AppData\Roaming\Python\Python37\site-packages\pyscreeze\__init__.py", line 578, in pixel
    color = windll.gdi32.GetPixel(hdc, x, y)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: Don't know how to convert parameter 2`

**Comment by ThreePiMatt** [comment]
Ran into this issue myself. It seems that this is only an issue if you have the opencv-python module installed.

**Comment by michaelkozin** [comment]
same for me, 
px = pyautogui.pixel(x, y) gives this error:
color = windll.gdi32.GetPixel(hdc, x, y)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: Don't know how to convert parameter 2

I also have opencv-python installed

I also have

**Comment by JayRizzo** [comment]
The TypeError might be to receiving a NULL value or None.  

I think this might be related to change in default behaviour. 

```python
int(None)
# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
# TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

See my writeup here from another issue i found and created a PR for: https://github.com/asweigart/pyautogui/issues/690#issue-1205346679

**Comment by TranqStyle** [comment]
I was also having this error:
```
color = windll.gdi32.GetPixel(hdc, x, y)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: Don't know how to convert parameter 2
```
Casting the parameters to int as follows solved my problem:
`px = pyautogui.pixel(int(x), int(y))`
