### ISSUE TITLE
Error on import pyautogui on linux based raspi

### ISSUE THREAD

**Issue by Bishamon1987** [asweigart/pyautogui#382]
I'm running this script after installing
pip3, pillow and pyautogui

Setup: raspi 3B+ with monitor via HDMI running in X11

 ```
pi@CRANKSHAFT-NG:~ $ python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pyautogui
  File "/home/pi/.local/lib/python3.5/site-packages/pyautogui/__init__.py", line 94, in <module>
    import mouseinfo
  File "/home/pi/.local/lib/python3.5/site-packages/mouseinfo/__init__.py", line 149, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
```

How can i solve this?

**Comment by Bishamon1987** [comment]
i tried to use 
`export DISPLAY=:0`
this gave me more errors
`pi@CRANKSHAFT-NG:~ $ python3 test.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Xlib/xauth.py", line 43, in __init__
    raw = open(filename, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.Xauthority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pyautogui
  File "/usr/local/lib/python3.5/dist-packages/pyautogui/__init__.py", line 94, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.5/dist-packages/mouseinfo/__init__.py", line 149, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.5/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.5/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/local/lib/python3.5/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/local/lib/python3.5/dist-packages/Xlib/support/connect.py", line 91, in get_auth
    return mod.get_auth(sock, dname, host, dno)
  File "/usr/local/lib/python3.5/dist-packages/Xlib/support/unix_connect.py", line 103, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/local/lib/python3.5/dist-packages/Xlib/xauth.py", line 45, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 2] No such file or directory: '/home/pi/.Xauthority'`
