### ISSUE TITLE
Locatiing but not clicking images on IE

### ISSUE THREAD

**Issue by mayurpande** [asweigart/pyautogui#384]
I am using python 3.6 and pyautogui version 0.9.41

It is working fine everywhere else, but when I have a IE browser open it locates images successfully and I am able to print the locations to set it, but then I use the `click` function it does nothing. But then doesn't treat it as an error. 

I have tested without using images to click for example a random location on the screen like so;

```
pyautogui.click(100,400)
```
and it does nothing, but when I minimise the browser and run the program I see that it performs the click.

I am not sure what is going on

**Comment by mayurpande** [comment]
Ok I have sort of found out why it is not working, so when the IE browser open in the task bar the IE icon is selected, if I de-select it, it is able to click the windows menu button, but it does not allow it when it is selected. Is there a way to solve this?

**Comment by JayRizzo** [comment]
Have you tried using the moveTo?

    pyautogui.moveTo(100,400)

I have noticed that some things will require, `sleep` (waiting for things to load), `moveTo` move your mouse like a human would and not just magically click on that spot.

Also, try using a different version (0.9.44 works best for me.) or using a custom virtual environment.  as that helps as well.  

Let me know if any of those help.

Cheers!

**Comment by mayurpande** [comment]
> Have you tried using the moveTo?
> 
> ```
> pyautogui.moveTo(100,400)
> # Then
> pyautogui.click(100,400)
> ```
> 
> I have noticed that some things will require, `sleep(1)` (waiting for things to load), `moveTo` move your mouse like a human would and not just magically click on that spot.
> 
> Also, try using a different version (0.9.44 works best for me.) or using a custom virtual environment. as that helps as well.
> 
> Let me know if any of those help.
> 
> Cheers!

Hey @JayRizzo, I did try all of the things you suggested and it still thinks it clicked the item. It is very bizarre. As it works on a different machine and clicks are other images that are not in the IE browser

**Comment by naveenthammu** [comment]
### there is an issue with clicks the triple click is not working 
pyautogui.tripleClick()
_**error is raising**
**Traceback (most recent call last):_
  File "/Users/naveen_stark/p.py", line 2, in <module>
    import pydirectinput
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydirectinput/__init__.py", line 6, in <module>
    SendInput = ctypes.windll.user32.SendInput
AttributeError: module 'ctypes' has no attribute 'windll'**

### if i use clicks 
pyautogui.Click(clicks=3,duration=.5)
### there is no responce in this

**Comment by sidharthpunathil** [comment]
I am having the same issue. It is moving to the location but is not clicking.

pyautogui.moveTo(106,57,1)
pyautogui.click(106,57,1)

**Comment by JayRizzo** [comment]
Hi @naveenthammu,  

I hope you are doing well.  I am using the newest release of Python 3.9 and pyautogui '0.9.53'  and I am unable to reproduce this error.  Are you still experiencing this as an issue?

Have a Great Day!

**Comment by jigyasu2004** [comment]
> Ok I have sort of found out why it is not working, so when the IE browser open in the task bar the IE icon is selected, if I de-select it, it is able to click the windows menu button, but it does not allow it when it is selected. Is there a way to solve this?

same problem did you solve this?
