### ISSUE TITLE
locate function always returns None

### ISSUE THREAD

**Issue by christophervalles** [asweigart/pyautogui#4]
I did a screenshot of my screen on mac (entire display) and then cropped a small area. Used those images on the locate function always returns None.

```
print pyautogui.locate('button.png', 'screengrab.png', grayscale=True)
```

**Comment by jeremygray** [comment]
`locate()` functions are working for me with the latest code from asweigert/pyautogui/master on Mac 10.9.5, python 2.7.8. I used Cmd-Shift-4 to capture a needle image (attached), saved as a default "Screenshot date - time.png", no further processing or format conversion (no Photoshop, etc). The coordinates are off by a factor of 2 (due to retina display, probably).

![screen shot 2015-01-06 at 12 29 08 pm](https://cloud.githubusercontent.com/assets/382342/5635617/a8fa0050-95b8-11e4-98e9-f4d15c584815.png)

**Comment by rrmhearts** [comment]
I love your software! However, I am having a similar problem. Sometimes, Windows provides "flashing" buttons (animated) and the software has a hard time finding it, even with multiple instances of the button to look for. So, I think it would be nice to have a tolerance argument to match at less than 100%.
Thanks for this tool!

**Comment by rgester** [comment]
@asweigart thank you for a great tool. Very helpful comment from @jeremygray. I have the same issue on OSX and retina display (coordinates are off by a factor of 2). I first thought the matching had gone bananas, but the factor 2 was a perfect explanation for me. Hope it can be fixed in later versions.

**Comment by artagel** [comment]
I can't seem to get the locate to work even when I take a screengrab with cmd+shift+4 of the button. Tried both python 2.7.10 and 3.5 on 2 different Macbook Pros.

**Comment by tcstang** [comment]
Same problem as @artagel on iMac.

locateOnScreen('button.jpeg') just freezes until I send a SIGTERM.

**Comment by raflman** [comment]
I think one of the reasons apart from ones mentioned here, correct me if I am mistaken, there are two functions that locates images on screen according to given image file which are _locateAll_python and _locateAll_opencv, I have inserted print functions in, to see which one of them gets called, when running on virtualenv python one gets called and occasionaly fails to locate and returns None.But using python installed on system and opencv installed, _locateAll_opencv gets called and does a pretty good job against _locateAll_python.(With the same image file.)

**Comment by davidcryptic** [comment]
I'm rather surprised that there isn't a "tolerance" option for "pyautogui.locateOnScreen." How difficult is that to implement? It seems like a rather key feature as rendering, animations, transparencies, etc. can all cause slight changes. Only being able to do pixel-perfect searches is very limiting.

**Comment by jeremygray** [comment]
_locateAll_opencv (in pyscreeze) accepts a confidence parameter, should be easy to expose that.

**Comment by imlordeyaya** [comment]
something like this definitely needs "tolerance" for finding pictures.

**Comment by halfskeed** [comment]
Yes please @asweigart, implementing a "tolerance" argument for `pyautogui.locateCenterOnScreen()` and similar `locate` functions would be very helpful, as I am having a problem getting color perfect matches for the same image in my program.

**Comment by jeremygray** [comment]
I started a new issue (#150) for this feature request, to keep the issues separate

**Comment by BorisMolch** [comment]
I am running on MacOS 10.12
LocateOnScreen() returns None everytime. Tried a few cropped non animated buttons that are clearly on screen when I run.
Any help ?

**Comment by kb1900** [comment]
macos 10.12 here

locateonscreen() is returning the wrong coordinates for my .png. seems to be completely off each time  regardless of what object i'm trying to find. seems to be a mac-specific issue

**Comment by BorisMolch** [comment]
Note: (had to tweak some functions but some things to note when on retina )
https://medium.com/@tracy_blog/pyautogui-and-retina-displays-2d5c37a5aa5e

**Comment by parkhe** [comment]
As in my case, I did hit a screenshot of a button (in a web form) and saved the reference images in 3 different formats/types: PNG, JPG and GIF. Only the first one worked. I believe this is due to 'pixel-perfect' requirement.

**Comment by pythonadventurer** [comment]
For what it's worth, I solved this problem for myself in Windows 10 by turning off "Transparency Effects" in Themes and Related Settings => Colors.

**Comment by suhas2686** [comment]
@pythonadventurer Thanks, turning off transparency effects and later saving the image as PNG worked.

**Comment by Dru808** [comment]
Having issues with the pyautogui.locateOnScreen. If I take a screen shot with comm + shift + 4 OR thru the pyautogui.screenshot() method, the first search would be found. 
However when the window of the image closes and refreshes, the search doesn't work anymore. 

Anyone found a fix to this yet? 

From researching for the answers, people are saying it has to be a pixel perfect match. 

is there any work arounds for this?

**Comment by im-Nky** [comment]
It's working fine with windows but in ubuntu most of function of this library get fails. Kindly help



Traceback (most recent call last):
  File "loc.py", line 2, in <module>
    x,y = pyautogui.locateCenterOnScreen('1.png')
  File "/usr/local/lib/python3.6/dist-packages/pyscreeze/__init__.py", line 295, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyscreeze/__init__.py", line 265, in locateOnScreen
    screenshotIm = screenshot(region=None) # the locateAll() function must handle cropping to return accurate coordinates, so don't pass a region here.
  File "/usr/local/lib/python3.6/dist-packages/pyscreeze/__init__.py", line 355, in _screenshot_linux
    im = Image.open(tmpFilename)
NameError: name 'Image' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "loc.py", line 2, in <module>
    x,y = pyautogui.locateCenterOnScreen('1.png')
  File "/usr/local/lib/python3.6/dist-packages/pyscreeze/__init__.py", line 295, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyscreeze/__init__.py", line 265, in locateOnScreen
    screenshotIm = screenshot(region=None) # the locateAll() function must handle cropping to return accurate coordinates, so don't pass a region here.
  File "/usr/local/lib/python3.6/dist-packages/pyscreeze/__init__.py", line 355, in _screenshot_linux
    im = Image.open(tmpFilename)
NameError: name 'Image' is not defined
![1](https://user-images.githubusercontent.com/31594344/45416630-f61cbf80-b69d-11e8-8788-f49f44ecd487.png)



this is my testing icon for which I'm trying perform operation.
