### ISSUE TITLE
AttributeError on mac

### ISSUE THREAD

**Issue by ziaoang** [asweigart/pyautogui#417]
Mac Version: macOs Catalina 10.15.3

```
>>> pyautogui.click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyautogui/__init__.py", line 588, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyautogui/__init__.py", line 978, in click
    platformModule._multiClick(x, y, button, clicks)
  File "/usr/local/lib/python3.7/site-packages/pyautogui/_pyautogui_osx.py", line 516, in _multiClick
    core_graphics.CGEventPost(kCGEvent.Tap.value, mouseEvent)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: Tap
```

**Comment by bregan23** [comment]
I got the same error, Python 3.8.2, macOS Sierra 10.12.6

**Comment by ShumaoZ** [comment]
Got the same error on all click-related operations e.g. click(), LeftClick(), RightClick(), DoubleClick() etc. Other functions are fine.

Environment: python 3.7.4, macOS Catalina 10.15.4.

**Comment by osfunapps** [comment]
I found a simple solution to make a left click button work for now.

In `_pyautogui_osx.py` change:
```
    mouseEvent = core_graphics.CGEventCreateMouseEvent(None, down.value, CGPoint(x, y), btn.value)
    core_graphics.CGEventSetIntegerValueField(mouseEvent, kCGMouseEvent.ClickState.value, num)
    core_graphics.CGEventPost(kCGEvent.d.value, mouseEvent)
    core_graphics.CGEventSetType(mouseEvent, up.val)
    core_graphics.CGEventPost(kCGEvent.Tap.value, mouseEvent)
    for i in range(0, num-1):
        core_graphics.CGEventSetType(mouseEvent, down.val)
        core_graphics.CGEventPost(kCGEvent.Tap.value, mouseEvent)
        core_graphics.CGEventSetType(mouseEvent, up.val)
        core_graphics.CGEventPost(kCGEvent.Tap.value, mouseEvent)
```

to:
```
    mouseEvent = core_graphics.CGEventCreateMouseEvent(None, down.value, CGPoint(x, y), btn.value)
    core_graphics.CGEventSetIntegerValueField(mouseEvent, kCGMouseEvent.ClickState.value, num)
    core_graphics.CGEventPost(kCGEvent.LeftMouseDown.value, mouseEvent)
    # core_graphics.CGEventSetType(mouseEvent, up.val)
    core_graphics.CGEventPost(kCGEvent.LeftMouseUp.value, mouseEvent)
    # for i in range(0, num-1):
    #     core_graphics.CGEventSetType(mouseEvent, down.val)
    #     core_graphics.CGEventPost(kCGEvent.Tap.value, mouseEvent)
    #     core_graphics.CGEventSetType(mouseEvent, up.val)
    #     core_graphics.CGEventPost(kCGEvent.Tap.value, mouseEvent)
```

The exception pops because there is no enum name Tap. So just replace it with key down and key up

**Comment by asweigart** [comment]
The changes that started this have all been rolled back in 0.9.50.
