### ISSUE TITLE
Help !! can't install pyautogui

### ISSUE THREAD

**Issue by aaronstone007** [asweigart/pyautogui#433]
**Command:**
----------------
`C:\Users\V!GN3$H>pip install pyautogui`

**Output:**
-----------
```
Collecting pyautogui
  Using cached PyAutoGUI-0.9.50.tar.gz (57 kB)
Collecting pymsgbox
  Using cached PyMsgBox-1.0.8.tar.gz (18 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 2:
   command: 'E:\Python3\python.exe' 'E:\Python3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\V!GN3$H\AppData\Local\Temp\pip-build-env-abh7mmkd\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (43 lines):
  Collecting setuptools>=40.8.0
    Using cached setuptools-46.4.0-py3-none-any.whl (583 kB)
  Collecting wheel
    Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
  Installing collected packages: setuptools, wheel
  ERROR: Exception:
  Traceback (most recent call last):
    File "E:\Python3\lib\distutils\util.py", line 204, in subst_vars
      return re.sub(r'\$([a-zA-Z_][a-zA-Z_0-9]*)', _subst, s)
    File "E:\Python3\lib\re.py", line 208, in sub
      return _compile(pattern, flags).sub(repl, string, count)
    File "E:\Python3\lib\distutils\util.py", line 201, in _subst
      return os.environ[var_name]
    File "E:\Python3\lib\os.py", line 675, in __getitem__
      raise KeyError(key) from None
  KeyError: 'H'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "E:\Python3\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in _main
      status = self.run(options, args)
    File "E:\Python3\lib\site-packages\pip\_internal\cli\req_command.py", line 185, in wrapper
      return func(self, options, args)
    File "E:\Python3\lib\site-packages\pip\_internal\commands\install.py", line 398, in run
      installed = install_given_reqs(
    File "E:\Python3\lib\site-packages\pip\_internal\req\__init__.py", line 67, in install_given_reqs
      requirement.install(
    File "E:\Python3\lib\site-packages\pip\_internal\req\req_install.py", line 769, in install
      scheme = get_scheme(
    File "E:\Python3\lib\site-packages\pip\_internal\locations.py", line 185, in get_scheme
      scheme = distutils_scheme(
    File "E:\Python3\lib\site-packages\pip\_internal\locations.py", line 125, in distutils_scheme
      i.finalize_options()
    File "E:\Python3\lib\distutils\command\install.py", line 307, in finalize_options
      self.expand_basedirs()
    File "E:\Python3\lib\distutils\command\install.py", line 475, in expand_basedirs
      self._expand_attrs(['install_base', 'install_platbase', 'root'])
    File "E:\Python3\lib\distutils\command\install.py", line 469, in _expand_attrs
      val = subst_vars(val, self.config_vars)
    File "E:\Python3\lib\distutils\util.py", line 206, in subst_vars
      raise ValueError("invalid variable '$%s'" % var)
  ValueError: invalid variable '$'H''
  ----------------------------------------
ERROR: Command errored out with exit status 2: 'E:\Python3\python.exe' 'E:\Python3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\V!GN3$H\AppData\Local\Temp\pip-build-env-abh7mmkd\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by a1eaiactaest** [comment]
try:
`pip install pyautogui --user`
