### ISSUE TITLE
Running example from ReadTheDocs page getting error

### ISSUE THREAD

**Issue by DaveHCL** [asweigart/pyautogui#461]
Hello,
This tool came into my view as I need to automate some software installation. So I am running through the examples from the docs and am seeing the following:
>>> pyautogui.click("button.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\pyautogui\__init__.py", line 588, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "C:\Python37\lib\site-packages\pyautogui\__init__.py", line 970, in click
    x, y = _normalizeXYArgs(x, y)
  File "C:\Python37\lib\site-packages\pyautogui\__init__.py", line 651, in _normalizeXYArgs
    location = locateOnScreen(firstArg)
  File "C:\Python37\lib\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Python37\lib\site-packages\pyautogui\__init__.py", line 213, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
  File "C:\Python37\lib\site-packages\pyscreeze\__init__.py", line 360, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
  File "C:\Python37\lib\site-packages\pyscreeze\__init__.py", line 340, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "C:\Python37\lib\site-packages\pyscreeze\__init__.py", line 249, in _locateAll_python
    needleFileObj = open(needleImage, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'button.png'

But:
C:\Users\me\Desktop>ls button.png
button.png

I am on Win10 Pro running Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32.

Did I mess something up?

Please let me know,
Dave

**Comment by return007** [comment]
Maybe try specifying full / relative path.

**Comment by DaveHCL** [comment]
Hello,
I put in the full path and got this trace:
Traceback (most recent call last):
  File "C:/Users/david.hyer/PycharmProjects/AutomationProjectForSupport/pyautogui_example_1.py", line 11, in <module>
    pyautogui.click('C:\\Users\\david.hyer\\Desktop\\button.png') # Find where button.png appears on the screen and click it.
  File "C:\Python37\lib\site-packages\pyautogui\__init__.py", line 588, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "C:\Python37\lib\site-packages\pyautogui\__init__.py", line 970, in click
    x, y = _normalizeXYArgs(x, y)
TypeError: cannot unpack non-iterable NoneType object

Should I put the button.png at the above lines (100,200) location? Or find the x,y for where it is on my desktop and put those values in?
Thanks
