### ISSUE TITLE
Windows 977 Overlapped IO Operation 

### ISSUE THREAD

**Issue by yu210148** [asweigart/pyautogui#47]
Hi there,

Ran into an issue where a WindowsError: [Error 977] Overlapped I/O operation is in progress is thrown when trying to run the following code....

```
import pyautogui
import pypyodbc as pyodbc

def connect_to_wp():
    db = pyodbc.connect("DSN=db;UID=foo;PWD=bar")
    return db

def send_query(sql, db):
    q = db.cursor()
    q.execute(sql)
    return q

def get_number_of_registers(location):
        ''' a function to get the number of registers for a location'''
        sql = "SELECT COUNT(*) FROM POS_Registers INNER JOIN Pos_Setup ON POS_Registers.POSID = Pos_Setup.POSID INNER JOIN Location on Pos_Setup.LocationID = Location.LocationID WHERE Location.ShortDescription = '" + location + "'"
        db = connect_to_wp()
        q = send_query(sql, db)
        for row in q:
                numberOfRegisters = row[0]
        return numberOfRegisters

def create_cashier_account(location, numberOfRegisters):

        # click on a blank spot in wpadmin to put focus there
        # for this to work you need to have modules 112 & 322
        # open with 112 in the forground
        pyautogui.moveTo(922, 181)
        pyautogui.click()

location = '1ST GEORGE'
numberOfRegisters = get_number_of_registers(location)
create_cashier_account(location, numberOfRegisters)
```

Here's the whole output:

```
Traceback (most recent call last):
  File "C:\Users\Kevin Lucas\Desktop\bug.py", line 35, in <module>
    create_cashier_account(location, numberOfRegisters)
  File "C:\Users\Kevin Lucas\Desktop\bug.py", line 31, in create_cashier_account

    pyautogui.click()
  File "C:\Python27\lib\site-packages\pyautogui\__init__.py", line 285, in click

    platformModule._click(x, y, 'left')
  File "C:\Python27\lib\site-packages\pyautogui\_pyautogui_win.py", line 437, in
 _click
    _sendMouseEvent(MOUSEEVENTF_LEFTCLICK, x, y)
  File "C:\Python27\lib\site-packages\pyautogui\_pyautogui_win.py", line 480, in
 _sendMouseEvent
    raise ctypes.WinError()
WindowsError: [Error 997] Overlapped I/O operation is in progress.
```

If I set a value for 'numberOfRegisters' it works fine but pulling from the database produces the error.  The call to click() does execute but it dumps out right after.  

This is on win7 with python 2.7.10 with piautogui installed from pip 0.9.30.

**Comment by CTPaHHuK-HEbA** [comment]
It intersects with this error [https://github.com/asweigart/pyautogui/issues/23](url)
