### ISSUE TITLE
pip install pyautogui

### ISSUE THREAD

**Issue by peterrwilson99** [asweigart/pyautogui#490]
After attempting to pip install pyautogui I had an error arise I have never seen with pip. I upgraded pip to the newest version and have tested on packages since. I am on Mac OS 10.14.6 with pip version 20.2.4. I don't believe its an error on my end, but if I am wrong let me know!

$ pip install pyautogui
Collecting pyautogui
  Using cached PyAutoGUI-0.9.52.tar.gz (55 kB)
Collecting pymsgbox
  Using cached PyMsgBox-1.0.9.tar.gz (18 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/ln/ht896ddd4_lgcjmcc6_xrpp80000gn/T/pip-build-env-nuob_lzv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/anaconda3/lib/python3.8/site-packages/pip/__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/opt/anaconda3/lib/python3.8/locale.py", line 16, in <module>
      import re
    File "/opt/anaconda3/lib/python3.8/re.py", line 145, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/ln/ht896ddd4_lgcjmcc6_xrpp80000gn/T/pip-build-env-nuob_lzv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by pranay1208** [comment]
Received the exact same error with Windows 10 as well

**Comment by SaltySeaDog2020** [comment]
Same

**Comment by geekyvyas** [comment]
@peterrwilson99 have you tried switching the interpreter ??
