### ISSUE TITLE
Syntax error on MacOS Big Sur 11.1

### ISSUE THREAD

**Issue by Raphael-Quinones** [asweigart/pyautogui#530]
Still not sure if it's the OS or Pycharm's fault

Here's the error:

`Traceback (most recent call last):
  File "/Users/raphael/PycharmProjects/Project/main.py", line 19, in <module>
    from pyautogui import click
  File "/Users/raphael/PycharmProjects/Project/venv/lib/python2.7/site-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/Users/raphael/PycharmProjects/Project/venv/lib/python2.7/site-packages/mouseinfo/__init__.py", line 100, in <module>
    from rubicon.objc import ObjCClass, CGPoint
  File "/Users/raphael/PycharmProjects/Project/venv/lib/python2.7/site-packages/rubicon/objc/__init__.py", line 3, in <module>
    from .runtime import (  # noqa: F401
  File "/Users/raphael/PycharmProjects/Project/venv/lib/python2.7/site-packages/rubicon/objc/runtime.py", line 785
    self.restype, *self.argtypes = ctypes_for_method_encoding(self.encoding)
                  ^
SyntaxError: invalid syntax
`

**Comment by rgagarinr** [comment]
I have the same with Catalina 10.15.7
