### ISSUE TITLE
Mac OS X 10.15.6 installation error

### ISSUE THREAD

**Issue by ssxcxS45XT** [asweigart/pyautogui#534]
I got the following error. Can it be fixed?

```
$ pip3 install pyautogui
Collecting pyautogui
  Using cached PyAutoGUI-0.9.52.tar.gz (55 kB)
Requirement already satisfied: pyobjc-core in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyautogui) (7.1)
Collecting pygetwindow>=0.0.5
  Using cached PyGetWindow-0.0.9.tar.gz (9.7 kB)
Collecting pyscreeze>=0.1.21
  Using cached PyScreeze-0.1.26.tar.gz (23 kB)
Requirement already satisfied: Pillow>=5.2.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyscreeze>=0.1.21->pyautogui) (8.1.0)
Collecting PyTweening>=1.0.1
  Using cached PyTweening-1.0.3.zip (15 kB)
Collecting mouseinfo
  Using cached MouseInfo-0.1.3.tar.gz (10 kB)
Collecting pymsgbox
  Using cached PyMsgBox-1.0.9.tar.gz (18 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/mktemp/pip-build-env-u4v9woel/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/__main__.py", line 23, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/mktemp/pip-build-env-u4v9woel/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by asweigart** [comment]
Sorry for the delay in responding to this. Does this issue still occur? From the error message, it looks like something is happening with pip rather than pymsgbox (one of pyautogui's dependencies). Could you try updating pip with `pip3 install -U pip` and running it again?

**Comment by JayRizzo** [comment]
Hi @asweigart  & @ssxcxS45XT,  

I just did a fresh install and had no issues on 3.10.5.  I had this issue after upgrading my OS as well.   I wrote more here about what steps I had done.  https://github.com/asweigart/pyautogui/issues/495#issuecomment-1172557674
