### ISSUE TITLE
Getting AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow' on import

### ISSUE THREAD

**Issue by S-W-H** [asweigart/pyautogui#598]
When attempting `import pyautogui`, I get the following error message and traceback:

```python
Traceback (most recent call last):

  File "<ipython-input-1-fa2587ca3a04>", line 1, in <module>
    import pyautogui

  File "/usr/lib/python3.9/site-packages/pyautogui/__init__.py", line 221, in <module>
    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__

AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'
```

I have checked the contents of `pyscreeze/__init__.py`, not just on my computer, but as it currently appears in the [pyscreeze repository](https://github.com/asweigart/pyscreeze/blob/master/pyscreeze/__init__.py) as well, and there really is no `locateOnWindow` function/class/etc. contained in it.

The problem might have been introduced by [this commit](https://github.com/asweigart/pyautogui/commit/9bae043786ab92fada3a5e27c4c35db406417c21) about 2-3 months ago. Strangely, however, I have not been able to find anyone else on the web experiencing it.

**Comment by nostep79** [comment]
you are not the only one. We updated to this release yesterday and it caused all our testing to fail.

**Comment by Zaedus** [comment]
Same here. It says this line is the problem
```
locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
```
And throws the same error.

**Comment by todoascoding** [comment]
@S-W-H @nostep79 @Zaedus 
I've tested it and found out why.

Open your console as Administrator.

**Comment by todoascoding** [comment]
@S-W-H @nostep79 @Zaedus
I've tested it and found out why.

Change your username to alphabet.

**Comment by Zaedus** [comment]
> @S-W-H @nostep79 @Zaedus
> I've tested it and found out why.
> 
> Change your username to alphabet.

I'm not sure what you mean? I should change my system user name to alphabet? That doesn't really seem like a practical fix.

**Comment by todoascoding** [comment]
> > @S-W-H @nostep79 @Zaedus
> > I've tested it and found out why.
> > Change your username to alphabet.
> 
> I'm not sure what you mean? I should change my system user name to alphabet? That doesn't really seem like a practical fix.

Doesn't it work the solution for you?
It seems like a Unicode folder issue.

I've got the same error message when my system user name isn't in English. If it is, it works fine.

Anyway, how about make a new account and try it.
You need only 5 mins to do it.

**Comment by XDDudeGuy** [comment]
\> I've got the same error message when my system user name isn't in English. If it is, it works fine.
I've got the same error and my username only consists of English letters so Idk.

**Comment by nanpuhaha** [comment]
I've got the same error. I call the pyautogui.locateOnScreen function, but result is the error below.
> `AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'`.

**There is NO `locateOnWindow` function on pyscreeze, but `pyscreeze.locateOnWindow` is used on `pyautogui.locateOnWindow`.** 
I think this is the reason.

https://github.com/asweigart/pyautogui/blob/5e4acb870f2e7ce0ea1927cc5188bc2f5ab7bbbc/pyautogui/__init__.py#L219

https://github.com/asweigart/pyscreeze/blob/0446e87235e0079f591f0c49ece7d487dedc2f9a/pyscreeze/__init__.py#L350

**Comment by JayRizzo** [comment]
Hi Everyone!  I hope everyone is doing well.   It looks like there is an easy fix for this one.

https://github.com/asweigart/pyautogui/blob/5e4acb870f2e7ce0ea1927cc5188bc2f5ab7bbbc/pyautogui/__init__.py#L221

Here on this line we just need to change

    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__

To This: 

    locateOnWindow.__doc__ = pyscreeze.locateOnScreen.__doc__

Update this and your inputs will **work**.   The `locateOnWindow` changed to `locateOnScreen`.  

++@asweigart, FYI

```
Tested on: Windows Version	10.0.19042 Build 19042
Current Python:        3.9.2
Current PyAutoGUI:     0.9.53
```

The file location for me was: 
'C:\\Users\\`{UserName}`\\AppData\\Roaming\\Python\\Python39\\site-packages\\pyautogui\\__init__.py'

Do not look in the 
`C:\Program Files\Python39` folders

**Comment by Zaedus** [comment]
Thank you! By any chance, has this already been submitted as a PR or already in the works to be modified directly on the main branch?

**Comment by S-W-H** [comment]
@JayRizzo : Thanks a lot for the proposed solution. But, as addressed by @nanpuhaha, isn't the problem somewhat deeper if there is no `locateOnWindow` function in `pyscreeze`? 

I mean, `pyautogui` is already importing `locateOnScreen`, including its docstring, from `pyscreeze` under its actual name here:   
https://github.com/asweigart/pyautogui/blob/5e4acb870f2e7ce0ea1927cc5188bc2f5ab7bbbc/pyautogui/__init__.py#L211-L216

Thus, I guess we do not need to import the `locateOnScreen` docstring again under a different name…? Here is some more context in the form of all of the lines dealing with the attempted import of `locateOnWindow` from `pyscreeze`. (These follow immediately after the above import of `locateOnScreen`.)
https://github.com/asweigart/pyautogui/blob/5e4acb870f2e7ce0ea1927cc5188bc2f5ab7bbbc/pyautogui/__init__.py#L217-L222

What I did to fix the issue for the time being was simply to comment out those five lines 217-221. So far, it also works.

@Zaedus : I can't find any current pull request dealing with this. But I also find it hard to submit one without knowing what was the intention of @asweigart for the `locateOnWindow` function.

**Comment by hhslepicka** [comment]
I run into this problem today and it was due to a newer pyautogui version with old pyscreeze.
A less relaxed condition on the dependency (https://github.com/asweigart/pyautogui/blob/master/setup.py#L36) would have avoided it.
Upgrading pyscreeze solved the issue for me.

**Comment by Be4th** [comment]
> Hi Everyone! I hope everyone is doing well. It looks like there is an easy fix for this one.
> 
> https://github.com/asweigart/pyautogui/blob/5e4acb870f2e7ce0ea1927cc5188bc2f5ab7bbbc/pyautogui/__init__.py#L221
> 
> Here on this line we just need to change
> 
> ```
> locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
> ```
> 
> To This:
> 
> ```
> locateOnWindow.__doc__ = pyscreeze.locateOnScreen.__doc__
> ```
> 
> Update this and your inputs will **work**. The `locateOnWindow` changed to `locateOnScreen`.
> 
> ++@asweigart, FYI
> 
> ```
> Tested on: Windows Version	10.0.19042 Build 19042
> Current Python:        3.9.2
> Current PyAutoGUI:     0.9.53
> ```
> 
> The file location for me was:
> 'C:\Users\`{UserName}`\AppData\Roaming\Python\Python39\site-packages\pyautogui\**init**.py'
> 
> Do not look in the
> `C:\Program Files\Python39` folders
Man thankyou so much

**Comment by sergiodantasz** [comment]
> Hi Everyone! I hope everyone is doing well. It looks like there is an easy fix for this one.
> 
> https://github.com/asweigart/pyautogui/blob/5e4acb870f2e7ce0ea1927cc5188bc2f5ab7bbbc/pyautogui/__init__.py#L221
> 
> Here on this line we just need to change
> 
> ```
> locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
> ```
> 
> To This:
> 
> ```
> locateOnWindow.__doc__ = pyscreeze.locateOnScreen.__doc__
> ```
> 
> Update this and your inputs will **work**. The `locateOnWindow` changed to `locateOnScreen`.
> 
> ++@asweigart, FYI
> 
> ```
> Tested on: Windows Version	10.0.19042 Build 19042
> Current Python:        3.9.2
> Current PyAutoGUI:     0.9.53
> ```
> 
> The file location for me was: 'C:\Users\`{UserName}`\AppData\Roaming\Python\Python39\site-packages\pyautogui\**init**.py'
> 
> Do not look in the `C:\Program Files\Python39` folders

VALEU PAI, SALVOU DEMAIS !! ESTAAMOS JUNTOS MEU REI ! EH NOIS

**Comment by abuzze** [comment]
You should update pyscreeze to at least 0.1.28. to fix this error.

`pip3 install pyscreeze -U`

**Comment by jpmoraes** [comment]
> 

Excellent answer. Then I just have to give a pip install flask

**Comment by avinash7903** [comment]
> locateOnWindow.__doc__ = pyscreeze.locateOnScreen.__doc__

thank you for your support it helps me to solve my problem
