### ISSUE TITLE
The click function return PermissionError [WinError 5] 

### ISSUE THREAD

**Issue by hugoesb** [asweigart/pyautogui#60]
I can not use click function in Windows 8.1. I get the follow message:
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    pyautogui.click(100,100)
  File "C:\Python34\lib\site-packages\pyautogui\__init__.py", line 362, in click
    platformModule._click(x, y, 'left')
  File "C:\Python34\lib\site-packages\pyautogui\_pyautogui_win.py", line 437, in _click
    _sendMouseEvent(MOUSEEVENTF_LEFTCLICK, x, y)
  File "C:\Python34\lib\site-packages\pyautogui\_pyautogui_win.py", line 480, in _sendMouseEvent
    raise ctypes.WinError()
PermissionError: [WinError 5] Acesso negado.

I guess the problem come out on Windows 8.1. The point is, can we do something to solve this?

**Comment by AWPelican** [comment]
I find the same problem running on a Windows 7 machine. Oddly enough, on my home Windows 10 PC I don't get the error. Only on my work laptop. I initially thought it had something to do with  permissions, but then I realized that the click was actually being sent, even though the exception was being thrown. Here's the output:

Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import pyautogui
>>> pyautogui.click()
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    pyautogui.click()
  File "C:\Users\jmaughan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pyautogui\__init__.py", line 362, in click
    platformModule._click(x, y, 'left')
  File "C:\Users\jmaughan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pyautogui\_pyautogui_win.py", line 437, in _click
    _sendMouseEvent(MOUSEEVENTF_LEFTCLICK, x, y)
  File "C:\Users\jmaughan\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pyautogui\_pyautogui_win.py", line 480, in _sendMouseEvent
    raise ctypes.WinError()
PermissionError: [WinError 5] Access is denied.
>>>

**Comment by hugoesb** [comment]
I "solved" doing:

1) Create a batch file calling the script Python
2) Create a shortcut os this batch file
3)  Set the shortcut to run as administrator (right click on shortcut -> choose Properties -> in the Shortcut tab, click Advanced -> select the checkbox "Run as administrator" -> click OK, OK)

**Comment by AWPelican** [comment]
That might be helpful, but it would be great to avoid admin privilege requirements. Computers at work don't allow admin privileges. What I've been doing is just a simple try/except that ignores the PermissionError. The click still is sent even though there's an exception happening. So unfortunately the batch file idea won't work for me.

**Comment by hugoesb** [comment]
A little bit strange! If I use try/except once it not works. But it works if I use:

`try:
    pg.doubleClick(1210,110)
except:
    try:
        pg.doubleClick(1210,110)
    except:
        pass`

**Comment by AWPelican** [comment]
The reason your double click fails is I think because it fails out after the first click of the two. The way I did it at my work computer was to wrap the click function like this:

```
def clickFix():
	try:
		pyautogui.click()
	except PermissionError:
		pass
	
def doubleClickFix():
	clickFix()
	clickFix()
```

I then just ended up using the moveTo() and moveRel() functions to get my pointer where I wanted it to be to make the click. I haven't evaluated whether the other parameters work correctly. I was just trying to get a quick script to work.

So it's functional only in that it will successfully get a click sent to the machine. What else it may or may not do, I don't know. 

I know it's evil to have an `except: pass`, so I at least made sure it was only a PermissionError that we were ignoring.

**Comment by asweigart** [comment]
I've merged Hugo's PR that fixes this, and also fixed the OSError [WinError 6] issue that happens on Python 3.6, but we should keep this issue open to figure out the original cause of these exceptions.

The new issue I was finding (on Python 3.6 64-bit on Windows 7) was this:

>>> pyautogui.click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\github\pyautogui\pyautogui\__init__.py", line 363, in click
    platformModule._click(x, y, 'left')
  File "C:\github\pyautogui\pyautogui\_pyautogui_win.py", line 456, in _click
    _sendMouseEvent(MOUSEEVENTF_LEFTCLICK, x, y)
  File "C:\github\pyautogui\pyautogui\_pyautogui_win.py", line 507, in _sendMouseEvent
    raise ctypes.WinError()
OSError: [WinError 6] The handle is invalid.

**Comment by 406322** [comment]
This issue is not happening in 2.7. Have anyone found a solution to this without the Try, Except forcing?
