### ISSUE TITLE
method pixelMatchesColor() raises an exception

### ISSUE THREAD

**Issue by comiluv** [asweigart/pyautogui#607]
Environment: Windows 10, python 3.9.6, PyAutoGUI 0.9.53

I was doing a programming project in chapter 20 of Automate Boring Stuff with Python called formFiller.py
Source code is as follows as in the book and also in the website https://automatetheboringstuff.com/2e/chapter20/
```python
# form_filler.py

import pyautogui, time

nameField = (527, 600)
submitButton = (570, 1747)
submitButtonColor = (119, 119, 119)
submitAnotherLink = (565, 405)

formData = [
    {
        "name": "Alice",
        "fear": "eavesdroppers",
        "source": "wand",
        "robocop": 4,
        "comments": "Tell Bob I said hi.",
    },
    {
        "name": "Bob",
        "fear": "bees",
        "source": "amulet",
        "robocop": 4,
        "comments": "n/a",
    },
    {
        "name": "Carol",
        "fear": "puppets",
        "source": "crystal ball",
        "robocop": 1,
        "comments": "Please take the puppets out of the break room.",
    },
    {
        "name": "Alex Murphy",
        "fear": "ED-209",
        "source": "money",
        "robocop": 5,
        "comments": "Protect the innocent. Serve the public trust. Uphold the law.",
    },
]

pyautogui.PAUSE = 0.5

print("Ensure that the browser window is active and the form is loaded!")

for person in formData:
    # Give the user a chance to kill the script.
    print(">>> 5-SECOND PAUSE TO LET USER PRESS CTRL-C <<<")
    time.sleep(5)

    # wait until the form page has loaded.
    while not pyautogui.pixelMatchesColor(
        submitButton[0], submitButton[1], submitButtonColor
    ):
        time.sleep(0.5)
    # Fill out the Name Field.
    print("Entering %s info..." % (person["name"],))
    pyautogui.click(nameField[0], nameField[1])

    pyautogui.write(person["name"] + "\t")

    # Fill out the Greatest Fear(s) field.
    pyautogui.write(person["fear"] + "\t")

    # Fill out the Source of Wizard Powers field.
    if person["source"] == "wand":
        pyautogui.write(["down", "\t"], 0.5)
    elif person["source"] == "amulet":
        pyautogui.write(["down", "down", "\t"], 0.5)
    elif person["source"] == "crystal ball":
        pyautogui.write(["down", "down", "down", "\t"], 0.5)
    elif person["source"] == "money":
        pyautogui.write(["down", "down", "down", "down", "\t"], 0.5)

    # Fill out the RoboCop field.
    if person["robocop"] == 1:
        pyautogui.write([" ", "\t"], 0.5)
    elif person["robocop"] == 2:
        pyautogui.write(["right", "\t", 0.5])
    elif person["robocop"] == 3:
        pyautogui.write(["right", "right", "\t"], 0.5)
    elif person["robocop"] == 4:
        pyautogui.write(["right", "right", "right", "\t"], 0.5)
    elif person["robocop"] == 5:
        pyautogui.write(["right", "right", "right", "right", "\t"], 0.5)

    # Fill out the Additional Comments field.
    pyautogui.write(person["comments"] + "\t")

    # Click Submit button by pressing Enter.
    time.sleep(0.5)
    pyautogui.press("enter")

    # Wait until form page has loaded.
    print("Submitted form.")
    time.sleep(5)

    # Click the Submit another response link.
    pyautogui.click(submitAnotherLink[0], submitAnotherLink[1])
```

When the python interpreter reached the while loop where it does an infinite loop until "Submit" button appears in the browser, the program raises an exception as below:
```python
Traceback (most recent call last):
  File "C:\Dev\automate_boring_stuff_with_python\ch20\formFiller.py", line 51, in <module>
    while not pyautogui.pixelMatchesColor(
  File "C:\Users\choij\AppData\Roaming\Python\Python39\site-packages\pyscreeze\__init__.py", line 588, in pixelMatchesColor
    pix = pixel(x, y)
  File "C:\Users\choij\AppData\Roaming\Python\Python39\site-packages\pyscreeze\__init__.py", line 613, in pixel
    return (r, g, b)
  File "C:\Python39\lib\contextlib.py", line 124, in __exit__
    next(self.gen)
  File "C:\Users\choij\AppData\Roaming\Python\Python39\site-packages\pyscreeze\__init__.py", line 122, in __win32_openDC
    raise WindowsError("windll.user32.ReleaseDC failed : return 0")
OSError: windll.user32.ReleaseDC failed : return 0
The terminal process "C:\Users\choij\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe -NoProfile -Command chcp 65001 > $null && py ./formFiller.py" terminated with exit code: 1.
```
And the program fails to continue.

**Comment by NYPDK** [comment]
Same issue here: Python 3.9.7

**Comment by NYPDK** [comment]
Found a fix https://github.com/asweigart/pyscreeze/pull/73

**Comment by asweigart** [comment]
With the fix for https://github.com/asweigart/pyscreeze/pull/73 in PyScreeze, this issue should be fixed. Just do a `pip install -U pyscreeze` to install the latest version of PyScreeze (1.0.28 has the fix). Thank you so much for pointing out this issue and the fix.
