### ISSUE TITLE
Running PyAutoGUI on MacOS doesn't work

### ISSUE THREAD

**Issue by AshIsbitt** [asweigart/pyautogui#622]
(Python 3.9, PyAutoGUI 0.9.53, Mac OS 11.5) Unable to run any python code that has pyautogui in, getting this error:

> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyautogui/_pyautogui_osx.py", line 5, in <module>
    import Quartz
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Quartz/__init__.py", line 6, in <module>
    import AppKit
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/AppKit/__init__.py", line 10, in <module>
    import Foundation
ModuleNotFoundError: No module named 'Foundation'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/Users/ashisbitt/Desktop/AutomateTheBoringStuff/Ch.20 - Coltrolling Mouse & Keyboard w: GUI Automation/1-getScreenSize.py", line 3, in <module>
    import pyautogui
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyautogui/__init__.py", line 544, in <module>
    from . import _pyautogui_osx as platformModule
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyautogui/_pyautogui_osx.py", line 7, in <module>
    assert False, "You must first install pyobjc-core and pyobjc: https://pyautogui.readthedocs.io/en/latest/install.html"
AssertionError: You must first install pyobjc-core and pyobjc: https://pyautogui.readthedocs.io/en/latest/install.html

The linked page just talks about basic installation. I've updated pyobjc and pyobjc-core to the latest version (7.3) using pip3, and also tried installing Xcode based off a SO post I found. Neither of these helped. I've also tried the El Capitan fix listed in the link in the error, which has changed nothing in the error I'm getting. Pillow v8.3.2 is present on my python3 install in the same location

**Comment by AshIsbitt** [comment]
Cleared via fresh install of py3.9 and all relevant libraries
