### ISSUE TITLE
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

### ISSUE THREAD

**Issue by BluePlattypus** [asweigart/pyautogui#706]
**So the code i wrote:**
import pyautogui, time

while True:
    try:
        pyautogui.write('owo hunt')
        pyautogui.press('enter')
        time.sleep(1)
        pyautogui.write('owo sell all')
        pyautogui.press('enter')
        time.sleep(14)
    except:
        break

And i gives me this:
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Hunt_Script_v1.3\lol.py", line 1, in <module>
    import pyautogui, time
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pyautogui\__init__.py", line 183, in <module>
    import pyscreeze
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pyscreeze\__init__.py", line 45, in <module>
    import cv2, numpy
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\gapi\__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
[Finished in 0.586s]

**Comment by Sakshat234** [comment]
Hi were you able to solve the issue.Its very annoying!

**Comment by MRK4863** [comment]
Same here.
Please update if you get any solution

**Comment by BluePlattypus** [comment]
> Same here.
> 
> Please update if you get any solution
> 
> 

Actially i reinstalled my whole Python installation and that worked for me, but i had to install every Package new

**Comment by FabricioSausen** [comment]
I fixed it by simply upgrading my opencv-python from 4.5.*.* (not sure which version it was anymore) to the currently latest one, which is 4.6.0.66.

Summary: run `pip install -U opencv-python`.

**Comment by tsmiyamoto** [comment]
In my case, downgrading opencv-python to **4.5.5.64** solved the problem.

```shell
pip install opencv-python==4.5.5.64
```

**Comment by harrytrinh96** [comment]
Thank you guys!!

**Comment by JayRizzo** [comment]
FWIW, I just did a fresh install and had no issues on 3.10.5. 

I had this issue after upgrading my OS as well.   I wrote more here about what steps I had done: https://github.com/asweigart/pyautogui/issues/495#issuecomment-1172557674

**Comment by MRK4863** [comment]
Thank you guys!!

**Comment by jiluojiluo** [comment]
> In my case, downgrading opencv-python to **4.5.5.64** solved the problem.
> 
> ```shell
> pip install opencv-python==4.5.5.64
> ```

yes,it works

**Comment by MikakuU** [comment]
Thanks, it works for me, too.
