### ISSUE TITLE
mouseDown() on Windows causes ctypes.WinError() OSError: [WinError 1813] The specified resource type cannot be found in the image file.

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyautogui#76]
I got this bug report:

Hi, I get the following error when trying to use the pyautogui.mouseDown function in Python 3.4 in Windows:

Traceback (most recent call last):File "example.py", line 149, in <module>

create_CR()File "example.py", line 56, in create_CR

pyautogui.mouseDown(703, 248, 'left')File "C:\Python34\lib\site-packages\pyautogui-0.9.33-py3.4.egg\pyautogui__init__.py", line 274, in mouseDown

platformModule._mouseDown(x, y, 'left')File "C:\Python34\lib\site-packages\pyautogui-0.9.33-py3.4.egg\pyautogui_pyautogui_win.py", line 393, in _mouseDown

_sendMouseEvent(MOUSEEVENTF_LEFTDOWN, x, y)File "C:\Python34\lib\site-packages\pyautogui-0.9.33-py3.4.egg\pyautogui_pyautogui_win.py", line 480, in _sendMouseEvent

raise ctypes.WinError() OSError: [WinError 1813] The specified resource type cannot be found in the image file.

Any ideas? Thank you!

**Comment by asweigart** [comment]
Closed as these exceptions are now being suppressed. I'm not sure if GetLastError() is retrieving actual errors caused by pyautogui.
