### ISSUE TITLE
import error: module 'pyscreeze' has no attribute 'locateOnWindow'

### ISSUE THREAD

**Issue by jacopman** [asweigart/pyautogui#776]
<head>pip installs with no issue, however when running the code</head><br>
<code>Traceback (most recent call last):
  File "c:\Users\chubs\Documents\cs1410\python\main.py", line 1, in module
    import pyautogui
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyautogui\__init__.py", line 221, in <module>
    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'</code>
i've uninstalled and installed twice with no fix. anyone else having an issue?

**Comment by romaklym** [comment]
Have you tried doing:
`pip install PyScreeze`
