### ISSUE TITLE
installation via pip fails on headless machines

### ISSUE THREAD

**Issue by franekp** [asweigart/pyautogui#78]
Please don't call Xlib.Display constructor at module-level scope in _pyautogui_x11.py.

**Comment by hugoesb** [comment]
Run `pip install python-xlib` and after that install pyautogui.

**Comment by tracyoconnor** [comment]
I'm trying to install pyautogui on AWS ubuntu server.   I've installed python-xlib, but am getting a display connection error. Any ideas @hugoesb? 

Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    version=__import__('pyautogui').__version__,
  File "/home/ubuntu/pyautogui/pyautogui/__init__.py", line 115, in <module>
    from . import _pyautogui_x11 as platformModule
  File "/home/ubuntu/pyautogui/pyautogui/_pyautogui_x11.py", line 154, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, host, displayno)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/Xlib/support/connect.py", line 86, in get_socket
    return mod.get_socket(dname, host, dno)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/Xlib/support/unix_connect.py", line 96, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":0.0": [Errno 111] Connection refused

**Comment by dragon788** [comment]
@tracyoconnor have you tried using Xvfb as your display? See #54 for more musings.

**Comment by tracyoconnor** [comment]
@dragon788 yes!  So I installed Xvfb and set my virtual display and finally got it to work!! (and then did a happy dance)

**Comment by asweigart** [comment]
Currently PyAutoGUI doesn't support remote/headless machines. I've created a master issue #133 to track the development of this feature.
