### ISSUE TITLE
Unable to install pyautogui

### ISSUE THREAD

**Issue by ChillarAnand** [asweigart/pyautogui#96]
I have installed `pillow`, `python3-xlib`, ` python3-tk`, ` python3-dev`, `scrot`. Still not able to install pytautogui.

System details

```
→ uname -a
Linux pavilion 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 
chillaranand@pavilion:~/projects |
→ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
```

```
chillaranand@pavilion:~/projects |
→ pip install pillow               
Requirement already satisfied (use --upgrade to upgrade): pillow in /home/chillaranand/.virtualenvs/exp/lib/python3.5/site-packages

chillaranand@pavilion:~/projects |
→ sudo apt-get install python3-xlib
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-xlib is already the newest version (0.14+20091101-5).
0 upgraded, 0 newly installed, 0 to remove and 252 not upgraded.

chillaranand@pavilion:~/projects |
→ pip install pyautogui
Collecting pyautogui
  Using cached PyAutoGUI-0.9.33.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rrn7mnyl/pyautogui/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "/tmp/pip-build-rrn7mnyl/pyautogui/pyautogui/__init__.py", line 114, in <module>
        from . import _pyautogui_x11 as platformModule
      File "/tmp/pip-build-rrn7mnyl/pyautogui/pyautogui/_pyautogui_x11.py", line 6, in <module>
        from Xlib.display import Display
    ImportError: No module named 'Xlib'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rrn7mnyl/pyautogui/
```

**Comment by hugoesb** [comment]
You need pay attention about the Python you are installing and run: Python 2.x or Python 3.x. I guess your Ubuntu have Python 2.X and Python 3.X. If you want use pyautogui on Python 3.X install `pillow` and `pyautogui` using `pip3`.

> $ pip3 install pillow
> $ pip3 install pyautogui

**Comment by ChillarAnand** [comment]
@hugoesb   I am able to install it system wide in both py2 & py3 with sudo. However I want to install them in virtualenv and it is failing with same error on py2 & py3.

**Comment by artburkart** [comment]
I was able to get it to install in a virtualenv on xenial after some effort.

```
$ python --version
Python 2.7.12

$ virtualenv -p `which python` venv
Running virtualenv with interpreter /usr/bin/python
New python executable in /home/artburkart/Code/venv/bin/python
Installing setuptools, pip, wheel...done.

$ . venv/bin/activate

(venv) $ sudo apt install python-xlib python-tk
(venv) $ pip install Image
(venv) $ pip install python-xlib
(venv) $ pip install Image
```

Only after installing these extra dependencies, could I get it to work.

**Comment by ChillarAnand** [comment]
Weird. Without any changes, it is working now. 

Thanks @hugoesb @artburkart  for the help.

**Comment by aggarwaldeepak** [comment]
pyautogui depends on xlib
Run
`sudo apt-get install python3-xlib`
`sudo pip3 install pyautogui`

**Comment by midnightsun183** [comment]
If you're still stuck, go here:

* https://medium.com/@tracy_blog/pyautogui-installing-on-mac-os-x-86e397428b3
